// Code generated by go-swagger; DO NOT EDIT.

package anomaly_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAnomalyNotificationParams creates a new GetAnomalyNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAnomalyNotificationParams() *GetAnomalyNotificationParams {
	return &GetAnomalyNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAnomalyNotificationParamsWithTimeout creates a new GetAnomalyNotificationParams object
// with the ability to set a timeout on a request.
func NewGetAnomalyNotificationParamsWithTimeout(timeout time.Duration) *GetAnomalyNotificationParams {
	return &GetAnomalyNotificationParams{
		timeout: timeout,
	}
}

// NewGetAnomalyNotificationParamsWithContext creates a new GetAnomalyNotificationParams object
// with the ability to set a context for a request.
func NewGetAnomalyNotificationParamsWithContext(ctx context.Context) *GetAnomalyNotificationParams {
	return &GetAnomalyNotificationParams{
		Context: ctx,
	}
}

// NewGetAnomalyNotificationParamsWithHTTPClient creates a new GetAnomalyNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAnomalyNotificationParamsWithHTTPClient(client *http.Client) *GetAnomalyNotificationParams {
	return &GetAnomalyNotificationParams{
		HTTPClient: client,
	}
}

/*
GetAnomalyNotificationParams contains all the parameters to send to the API endpoint

	for the get anomaly notification operation.

	Typically these are written to a http.Request.
*/
type GetAnomalyNotificationParams struct {

	// ReportAlertToken.
	ReportAlertToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get anomaly notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAnomalyNotificationParams) WithDefaults() *GetAnomalyNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get anomaly notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAnomalyNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get anomaly notification params
func (o *GetAnomalyNotificationParams) WithTimeout(timeout time.Duration) *GetAnomalyNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get anomaly notification params
func (o *GetAnomalyNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get anomaly notification params
func (o *GetAnomalyNotificationParams) WithContext(ctx context.Context) *GetAnomalyNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get anomaly notification params
func (o *GetAnomalyNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get anomaly notification params
func (o *GetAnomalyNotificationParams) WithHTTPClient(client *http.Client) *GetAnomalyNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get anomaly notification params
func (o *GetAnomalyNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReportAlertToken adds the reportAlertToken to the get anomaly notification params
func (o *GetAnomalyNotificationParams) WithReportAlertToken(reportAlertToken string) *GetAnomalyNotificationParams {
	o.SetReportAlertToken(reportAlertToken)
	return o
}

// SetReportAlertToken adds the reportAlertToken to the get anomaly notification params
func (o *GetAnomalyNotificationParams) SetReportAlertToken(reportAlertToken string) {
	o.ReportAlertToken = reportAlertToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetAnomalyNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param report_alert_token
	if err := r.SetPathParam("report_alert_token", o.ReportAlertToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
