// Code generated by go-swagger; DO NOT EDIT.

package managed_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetManagedAccountsReader is a Reader for the GetManagedAccounts structure.
type GetManagedAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetManagedAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetManagedAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /managed_accounts] getManagedAccounts", response, response.Code())
	}
}

// NewGetManagedAccountsOK creates a GetManagedAccountsOK with default headers values
func NewGetManagedAccountsOK() *GetManagedAccountsOK {
	return &GetManagedAccountsOK{}
}

/*
GetManagedAccountsOK describes a response with status code 200, with default header values.

GetManagedAccountsOK get managed accounts o k
*/
type GetManagedAccountsOK struct {
	Payload *models.ManagedAccounts
}

// IsSuccess returns true when this get managed accounts o k response has a 2xx status code
func (o *GetManagedAccountsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get managed accounts o k response has a 3xx status code
func (o *GetManagedAccountsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get managed accounts o k response has a 4xx status code
func (o *GetManagedAccountsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get managed accounts o k response has a 5xx status code
func (o *GetManagedAccountsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get managed accounts o k response a status code equal to that given
func (o *GetManagedAccountsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get managed accounts o k response
func (o *GetManagedAccountsOK) Code() int {
	return 200
}

func (o *GetManagedAccountsOK) Error() string {
	return fmt.Sprintf("[GET /managed_accounts][%d] getManagedAccountsOK  %+v", 200, o.Payload)
}

func (o *GetManagedAccountsOK) String() string {
	return fmt.Sprintf("[GET /managed_accounts][%d] getManagedAccountsOK  %+v", 200, o.Payload)
}

func (o *GetManagedAccountsOK) GetPayload() *models.ManagedAccounts {
	return o.Payload
}

func (o *GetManagedAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ManagedAccounts)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
