// Code generated by go-swagger; DO NOT EDIT.

package dashboard_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// NewUpdateDashboardNotificationParams creates a new UpdateDashboardNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDashboardNotificationParams() *UpdateDashboardNotificationParams {
	return &UpdateDashboardNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDashboardNotificationParamsWithTimeout creates a new UpdateDashboardNotificationParams object
// with the ability to set a timeout on a request.
func NewUpdateDashboardNotificationParamsWithTimeout(timeout time.Duration) *UpdateDashboardNotificationParams {
	return &UpdateDashboardNotificationParams{
		timeout: timeout,
	}
}

// NewUpdateDashboardNotificationParamsWithContext creates a new UpdateDashboardNotificationParams object
// with the ability to set a context for a request.
func NewUpdateDashboardNotificationParamsWithContext(ctx context.Context) *UpdateDashboardNotificationParams {
	return &UpdateDashboardNotificationParams{
		Context: ctx,
	}
}

// NewUpdateDashboardNotificationParamsWithHTTPClient creates a new UpdateDashboardNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDashboardNotificationParamsWithHTTPClient(client *http.Client) *UpdateDashboardNotificationParams {
	return &UpdateDashboardNotificationParams{
		HTTPClient: client,
	}
}

/*
UpdateDashboardNotificationParams contains all the parameters to send to the API endpoint

	for the update dashboard notification operation.

	Typically these are written to a http.Request.
*/
type UpdateDashboardNotificationParams struct {

	// DashboardNotificationToken.
	DashboardNotificationToken string

	// UpdateDashboardNotification.
	UpdateDashboardNotification *models.UpdateDashboardNotification

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update dashboard notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDashboardNotificationParams) WithDefaults() *UpdateDashboardNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update dashboard notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDashboardNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) WithTimeout(timeout time.Duration) *UpdateDashboardNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) WithContext(ctx context.Context) *UpdateDashboardNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) WithHTTPClient(client *http.Client) *UpdateDashboardNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDashboardNotificationToken adds the dashboardNotificationToken to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) WithDashboardNotificationToken(dashboardNotificationToken string) *UpdateDashboardNotificationParams {
	o.SetDashboardNotificationToken(dashboardNotificationToken)
	return o
}

// SetDashboardNotificationToken adds the dashboardNotificationToken to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) SetDashboardNotificationToken(dashboardNotificationToken string) {
	o.DashboardNotificationToken = dashboardNotificationToken
}

// WithUpdateDashboardNotification adds the updateDashboardNotification to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) WithUpdateDashboardNotification(updateDashboardNotification *models.UpdateDashboardNotification) *UpdateDashboardNotificationParams {
	o.SetUpdateDashboardNotification(updateDashboardNotification)
	return o
}

// SetUpdateDashboardNotification adds the updateDashboardNotification to the update dashboard notification params
func (o *UpdateDashboardNotificationParams) SetUpdateDashboardNotification(updateDashboardNotification *models.UpdateDashboardNotification) {
	o.UpdateDashboardNotification = updateDashboardNotification
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDashboardNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dashboard_notification_token
	if err := r.SetPathParam("dashboard_notification_token", o.DashboardNotificationToken); err != nil {
		return err
	}
	if o.UpdateDashboardNotification != nil {
		if err := r.SetBodyParam(o.UpdateDashboardNotification); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
