// Code generated by go-swagger; DO NOT EDIT.

package cost_alert_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetCostAlertEventReader is a Reader for the GetCostAlertEvent structure.
type GetCostAlertEventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCostAlertEventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCostAlertEventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /cost_alerts/{cost_alert_token}/events/{event_token}] getCostAlertEvent", response, response.Code())
	}
}

// NewGetCostAlertEventOK creates a GetCostAlertEventOK with default headers values
func NewGetCostAlertEventOK() *GetCostAlertEventOK {
	return &GetCostAlertEventOK{}
}

/*
GetCostAlertEventOK describes a response with status code 200, with default header values.

GetCostAlertEventOK get cost alert event o k
*/
type GetCostAlertEventOK struct {
	Payload *models.CostAlertEvent
}

// IsSuccess returns true when this get cost alert event o k response has a 2xx status code
func (o *GetCostAlertEventOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cost alert event o k response has a 3xx status code
func (o *GetCostAlertEventOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cost alert event o k response has a 4xx status code
func (o *GetCostAlertEventOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cost alert event o k response has a 5xx status code
func (o *GetCostAlertEventOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cost alert event o k response a status code equal to that given
func (o *GetCostAlertEventOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cost alert event o k response
func (o *GetCostAlertEventOK) Code() int {
	return 200
}

func (o *GetCostAlertEventOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cost_alerts/{cost_alert_token}/events/{event_token}][%d] getCostAlertEventOK %s", 200, payload)
}

func (o *GetCostAlertEventOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cost_alerts/{cost_alert_token}/events/{event_token}][%d] getCostAlertEventOK %s", 200, payload)
}

func (o *GetCostAlertEventOK) GetPayload() *models.CostAlertEvent {
	return o.Payload
}

func (o *GetCostAlertEventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CostAlertEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
