// Code generated by go-swagger; DO NOT EDIT.

package budget_alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// UpdateBudgetAlertReader is a Reader for the UpdateBudgetAlert structure.
type UpdateBudgetAlertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateBudgetAlertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateBudgetAlertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUpdateBudgetAlertNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /budget_alerts/{budget_alert_token}] updateBudgetAlert", response, response.Code())
	}
}

// NewUpdateBudgetAlertOK creates a UpdateBudgetAlertOK with default headers values
func NewUpdateBudgetAlertOK() *UpdateBudgetAlertOK {
	return &UpdateBudgetAlertOK{}
}

/*
UpdateBudgetAlertOK describes a response with status code 200, with default header values.

UpdateBudgetAlertOK update budget alert o k
*/
type UpdateBudgetAlertOK struct {
	Payload *models.BudgetAlert
}

// IsSuccess returns true when this update budget alert o k response has a 2xx status code
func (o *UpdateBudgetAlertOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update budget alert o k response has a 3xx status code
func (o *UpdateBudgetAlertOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update budget alert o k response has a 4xx status code
func (o *UpdateBudgetAlertOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update budget alert o k response has a 5xx status code
func (o *UpdateBudgetAlertOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update budget alert o k response a status code equal to that given
func (o *UpdateBudgetAlertOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update budget alert o k response
func (o *UpdateBudgetAlertOK) Code() int {
	return 200
}

func (o *UpdateBudgetAlertOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /budget_alerts/{budget_alert_token}][%d] updateBudgetAlertOK %s", 200, payload)
}

func (o *UpdateBudgetAlertOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /budget_alerts/{budget_alert_token}][%d] updateBudgetAlertOK %s", 200, payload)
}

func (o *UpdateBudgetAlertOK) GetPayload() *models.BudgetAlert {
	return o.Payload
}

func (o *UpdateBudgetAlertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BudgetAlert)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateBudgetAlertNotFound creates a UpdateBudgetAlertNotFound with default headers values
func NewUpdateBudgetAlertNotFound() *UpdateBudgetAlertNotFound {
	return &UpdateBudgetAlertNotFound{}
}

/*
UpdateBudgetAlertNotFound describes a response with status code 404, with default header values.

NotFound
*/
type UpdateBudgetAlertNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this update budget alert not found response has a 2xx status code
func (o *UpdateBudgetAlertNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update budget alert not found response has a 3xx status code
func (o *UpdateBudgetAlertNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update budget alert not found response has a 4xx status code
func (o *UpdateBudgetAlertNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update budget alert not found response has a 5xx status code
func (o *UpdateBudgetAlertNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update budget alert not found response a status code equal to that given
func (o *UpdateBudgetAlertNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update budget alert not found response
func (o *UpdateBudgetAlertNotFound) Code() int {
	return 404
}

func (o *UpdateBudgetAlertNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /budget_alerts/{budget_alert_token}][%d] updateBudgetAlertNotFound %s", 404, payload)
}

func (o *UpdateBudgetAlertNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /budget_alerts/{budget_alert_token}][%d] updateBudgetAlertNotFound %s", 404, payload)
}

func (o *UpdateBudgetAlertNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateBudgetAlertNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
