// Code generated by go-swagger; DO NOT EDIT.

package canvases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// UpdateCanvasReader is a Reader for the UpdateCanvas structure.
type UpdateCanvasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCanvasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateCanvasOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateCanvasBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateCanvasNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /canvases/{canvas_token}] updateCanvas", response, response.Code())
	}
}

// NewUpdateCanvasOK creates a UpdateCanvasOK with default headers values
func NewUpdateCanvasOK() *UpdateCanvasOK {
	return &UpdateCanvasOK{}
}

/*
UpdateCanvasOK describes a response with status code 200, with default header values.

UpdateCanvasOK update canvas o k
*/
type UpdateCanvasOK struct {
	Payload *models.Canvas
}

// IsSuccess returns true when this update canvas o k response has a 2xx status code
func (o *UpdateCanvasOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update canvas o k response has a 3xx status code
func (o *UpdateCanvasOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update canvas o k response has a 4xx status code
func (o *UpdateCanvasOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update canvas o k response has a 5xx status code
func (o *UpdateCanvasOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update canvas o k response a status code equal to that given
func (o *UpdateCanvasOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update canvas o k response
func (o *UpdateCanvasOK) Code() int {
	return 200
}

func (o *UpdateCanvasOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasOK %s", 200, payload)
}

func (o *UpdateCanvasOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasOK %s", 200, payload)
}

func (o *UpdateCanvasOK) GetPayload() *models.Canvas {
	return o.Payload
}

func (o *UpdateCanvasOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Canvas)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCanvasBadRequest creates a UpdateCanvasBadRequest with default headers values
func NewUpdateCanvasBadRequest() *UpdateCanvasBadRequest {
	return &UpdateCanvasBadRequest{}
}

/*
UpdateCanvasBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type UpdateCanvasBadRequest struct {
	Payload *models.Errors
}

// IsSuccess returns true when this update canvas bad request response has a 2xx status code
func (o *UpdateCanvasBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update canvas bad request response has a 3xx status code
func (o *UpdateCanvasBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update canvas bad request response has a 4xx status code
func (o *UpdateCanvasBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update canvas bad request response has a 5xx status code
func (o *UpdateCanvasBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update canvas bad request response a status code equal to that given
func (o *UpdateCanvasBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update canvas bad request response
func (o *UpdateCanvasBadRequest) Code() int {
	return 400
}

func (o *UpdateCanvasBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasBadRequest %s", 400, payload)
}

func (o *UpdateCanvasBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasBadRequest %s", 400, payload)
}

func (o *UpdateCanvasBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateCanvasBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCanvasNotFound creates a UpdateCanvasNotFound with default headers values
func NewUpdateCanvasNotFound() *UpdateCanvasNotFound {
	return &UpdateCanvasNotFound{}
}

/*
UpdateCanvasNotFound describes a response with status code 404, with default header values.

NotFound
*/
type UpdateCanvasNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this update canvas not found response has a 2xx status code
func (o *UpdateCanvasNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update canvas not found response has a 3xx status code
func (o *UpdateCanvasNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update canvas not found response has a 4xx status code
func (o *UpdateCanvasNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update canvas not found response has a 5xx status code
func (o *UpdateCanvasNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update canvas not found response a status code equal to that given
func (o *UpdateCanvasNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update canvas not found response
func (o *UpdateCanvasNotFound) Code() int {
	return 404
}

func (o *UpdateCanvasNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasNotFound %s", 404, payload)
}

func (o *UpdateCanvasNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /canvases/{canvas_token}][%d] updateCanvasNotFound %s", 404, payload)
}

func (o *UpdateCanvasNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateCanvasNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
