// Code generated by go-swagger; DO NOT EDIT.

package prices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPriceParams creates a new GetPriceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPriceParams() *GetPriceParams {
	return &GetPriceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPriceParamsWithTimeout creates a new GetPriceParams object
// with the ability to set a timeout on a request.
func NewGetPriceParamsWithTimeout(timeout time.Duration) *GetPriceParams {
	return &GetPriceParams{
		timeout: timeout,
	}
}

// NewGetPriceParamsWithContext creates a new GetPriceParams object
// with the ability to set a context for a request.
func NewGetPriceParamsWithContext(ctx context.Context) *GetPriceParams {
	return &GetPriceParams{
		Context: ctx,
	}
}

// NewGetPriceParamsWithHTTPClient creates a new GetPriceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPriceParamsWithHTTPClient(client *http.Client) *GetPriceParams {
	return &GetPriceParams{
		HTTPClient: client,
	}
}

/*
GetPriceParams contains all the parameters to send to the API endpoint

	for the get price operation.

	Typically these are written to a http.Request.
*/
type GetPriceParams struct {

	// ID.
	ID string

	// ProductID.
	ProductID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPriceParams) WithDefaults() *GetPriceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPriceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get price params
func (o *GetPriceParams) WithTimeout(timeout time.Duration) *GetPriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get price params
func (o *GetPriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get price params
func (o *GetPriceParams) WithContext(ctx context.Context) *GetPriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get price params
func (o *GetPriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get price params
func (o *GetPriceParams) WithHTTPClient(client *http.Client) *GetPriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get price params
func (o *GetPriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get price params
func (o *GetPriceParams) WithID(id string) *GetPriceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get price params
func (o *GetPriceParams) SetID(id string) {
	o.ID = id
}

// WithProductID adds the productID to the get price params
func (o *GetPriceParams) WithProductID(productID string) *GetPriceParams {
	o.SetProductID(productID)
	return o
}

// SetProductID adds the productId to the get price params
func (o *GetPriceParams) SetProductID(productID string) {
	o.ProductID = productID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param product_id
	if err := r.SetPathParam("product_id", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
