// Code generated by go-swagger; DO NOT EDIT.

package report_notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReportNotificationParams creates a new GetReportNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReportNotificationParams() *GetReportNotificationParams {
	return &GetReportNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReportNotificationParamsWithTimeout creates a new GetReportNotificationParams object
// with the ability to set a timeout on a request.
func NewGetReportNotificationParamsWithTimeout(timeout time.Duration) *GetReportNotificationParams {
	return &GetReportNotificationParams{
		timeout: timeout,
	}
}

// NewGetReportNotificationParamsWithContext creates a new GetReportNotificationParams object
// with the ability to set a context for a request.
func NewGetReportNotificationParamsWithContext(ctx context.Context) *GetReportNotificationParams {
	return &GetReportNotificationParams{
		Context: ctx,
	}
}

// NewGetReportNotificationParamsWithHTTPClient creates a new GetReportNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReportNotificationParamsWithHTTPClient(client *http.Client) *GetReportNotificationParams {
	return &GetReportNotificationParams{
		HTTPClient: client,
	}
}

/*
GetReportNotificationParams contains all the parameters to send to the API endpoint

	for the get report notification operation.

	Typically these are written to a http.Request.
*/
type GetReportNotificationParams struct {

	// ReportNotificationToken.
	ReportNotificationToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get report notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReportNotificationParams) WithDefaults() *GetReportNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get report notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReportNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get report notification params
func (o *GetReportNotificationParams) WithTimeout(timeout time.Duration) *GetReportNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get report notification params
func (o *GetReportNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get report notification params
func (o *GetReportNotificationParams) WithContext(ctx context.Context) *GetReportNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get report notification params
func (o *GetReportNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get report notification params
func (o *GetReportNotificationParams) WithHTTPClient(client *http.Client) *GetReportNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get report notification params
func (o *GetReportNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReportNotificationToken adds the reportNotificationToken to the get report notification params
func (o *GetReportNotificationParams) WithReportNotificationToken(reportNotificationToken string) *GetReportNotificationParams {
	o.SetReportNotificationToken(reportNotificationToken)
	return o
}

// SetReportNotificationToken adds the reportNotificationToken to the get report notification params
func (o *GetReportNotificationParams) SetReportNotificationToken(reportNotificationToken string) {
	o.ReportNotificationToken = reportNotificationToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetReportNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param report_notification_token
	if err := r.SetPathParam("report_notification_token", o.ReportNotificationToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
