// Code generated by go-swagger; DO NOT EDIT.

package enrichment_sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetEnrichmentSourceReader is a Reader for the GetEnrichmentSource structure.
type GetEnrichmentSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEnrichmentSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEnrichmentSourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetEnrichmentSourceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /enrichment_sources/{enrichment_source_token}] getEnrichmentSource", response, response.Code())
	}
}

// NewGetEnrichmentSourceOK creates a GetEnrichmentSourceOK with default headers values
func NewGetEnrichmentSourceOK() *GetEnrichmentSourceOK {
	return &GetEnrichmentSourceOK{}
}

/*
GetEnrichmentSourceOK describes a response with status code 200, with default header values.

GetEnrichmentSourceOK get enrichment source o k
*/
type GetEnrichmentSourceOK struct {
	Payload *models.EnrichmentSource
}

// IsSuccess returns true when this get enrichment source o k response has a 2xx status code
func (o *GetEnrichmentSourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get enrichment source o k response has a 3xx status code
func (o *GetEnrichmentSourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get enrichment source o k response has a 4xx status code
func (o *GetEnrichmentSourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get enrichment source o k response has a 5xx status code
func (o *GetEnrichmentSourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get enrichment source o k response a status code equal to that given
func (o *GetEnrichmentSourceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get enrichment source o k response
func (o *GetEnrichmentSourceOK) Code() int {
	return 200
}

func (o *GetEnrichmentSourceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrichment_sources/{enrichment_source_token}][%d] getEnrichmentSourceOK %s", 200, payload)
}

func (o *GetEnrichmentSourceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrichment_sources/{enrichment_source_token}][%d] getEnrichmentSourceOK %s", 200, payload)
}

func (o *GetEnrichmentSourceOK) GetPayload() *models.EnrichmentSource {
	return o.Payload
}

func (o *GetEnrichmentSourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnrichmentSource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEnrichmentSourceNotFound creates a GetEnrichmentSourceNotFound with default headers values
func NewGetEnrichmentSourceNotFound() *GetEnrichmentSourceNotFound {
	return &GetEnrichmentSourceNotFound{}
}

/*
GetEnrichmentSourceNotFound describes a response with status code 404, with default header values.

NotFound
*/
type GetEnrichmentSourceNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get enrichment source not found response has a 2xx status code
func (o *GetEnrichmentSourceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get enrichment source not found response has a 3xx status code
func (o *GetEnrichmentSourceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get enrichment source not found response has a 4xx status code
func (o *GetEnrichmentSourceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get enrichment source not found response has a 5xx status code
func (o *GetEnrichmentSourceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get enrichment source not found response a status code equal to that given
func (o *GetEnrichmentSourceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get enrichment source not found response
func (o *GetEnrichmentSourceNotFound) Code() int {
	return 404
}

func (o *GetEnrichmentSourceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrichment_sources/{enrichment_source_token}][%d] getEnrichmentSourceNotFound %s", 404, payload)
}

func (o *GetEnrichmentSourceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enrichment_sources/{enrichment_source_token}][%d] getEnrichmentSourceNotFound %s", 404, payload)
}

func (o *GetEnrichmentSourceNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetEnrichmentSourceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
