// Code generated by go-swagger; DO NOT EDIT.

package recommendations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetRecommendationsReader is a Reader for the GetRecommendations structure.
type GetRecommendationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRecommendationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRecommendationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /recommendations] getRecommendations", response, response.Code())
	}
}

// NewGetRecommendationsOK creates a GetRecommendationsOK with default headers values
func NewGetRecommendationsOK() *GetRecommendationsOK {
	return &GetRecommendationsOK{}
}

/*
GetRecommendationsOK describes a response with status code 200, with default header values.

GetRecommendationsOK get recommendations o k
*/
type GetRecommendationsOK struct {
	Payload *models.Recommendations
}

// IsSuccess returns true when this get recommendations o k response has a 2xx status code
func (o *GetRecommendationsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get recommendations o k response has a 3xx status code
func (o *GetRecommendationsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get recommendations o k response has a 4xx status code
func (o *GetRecommendationsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get recommendations o k response has a 5xx status code
func (o *GetRecommendationsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get recommendations o k response a status code equal to that given
func (o *GetRecommendationsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get recommendations o k response
func (o *GetRecommendationsOK) Code() int {
	return 200
}

func (o *GetRecommendationsOK) Error() string {
	return fmt.Sprintf("[GET /recommendations][%d] getRecommendationsOK  %+v", 200, o.Payload)
}

func (o *GetRecommendationsOK) String() string {
	return fmt.Sprintf("[GET /recommendations][%d] getRecommendationsOK  %+v", 200, o.Payload)
}

func (o *GetRecommendationsOK) GetPayload() *models.Recommendations {
	return o.Payload
}

func (o *GetRecommendationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Recommendations)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
