// Code generated by go-swagger; DO NOT EDIT.

package financial_commitment_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// CreateFinancialCommitmentReportReader is a Reader for the CreateFinancialCommitmentReport structure.
type CreateFinancialCommitmentReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFinancialCommitmentReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateFinancialCommitmentReportCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateFinancialCommitmentReportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateFinancialCommitmentReportUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /financial_commitment_reports] createFinancialCommitmentReport", response, response.Code())
	}
}

// NewCreateFinancialCommitmentReportCreated creates a CreateFinancialCommitmentReportCreated with default headers values
func NewCreateFinancialCommitmentReportCreated() *CreateFinancialCommitmentReportCreated {
	return &CreateFinancialCommitmentReportCreated{}
}

/*
CreateFinancialCommitmentReportCreated describes a response with status code 201, with default header values.

CreateFinancialCommitmentReportCreated create financial commitment report created
*/
type CreateFinancialCommitmentReportCreated struct {
	Payload *models.FinancialCommitmentReport
}

// IsSuccess returns true when this create financial commitment report created response has a 2xx status code
func (o *CreateFinancialCommitmentReportCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create financial commitment report created response has a 3xx status code
func (o *CreateFinancialCommitmentReportCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create financial commitment report created response has a 4xx status code
func (o *CreateFinancialCommitmentReportCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create financial commitment report created response has a 5xx status code
func (o *CreateFinancialCommitmentReportCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create financial commitment report created response a status code equal to that given
func (o *CreateFinancialCommitmentReportCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create financial commitment report created response
func (o *CreateFinancialCommitmentReportCreated) Code() int {
	return 201
}

func (o *CreateFinancialCommitmentReportCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportCreated %s", 201, payload)
}

func (o *CreateFinancialCommitmentReportCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportCreated %s", 201, payload)
}

func (o *CreateFinancialCommitmentReportCreated) GetPayload() *models.FinancialCommitmentReport {
	return o.Payload
}

func (o *CreateFinancialCommitmentReportCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FinancialCommitmentReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFinancialCommitmentReportBadRequest creates a CreateFinancialCommitmentReportBadRequest with default headers values
func NewCreateFinancialCommitmentReportBadRequest() *CreateFinancialCommitmentReportBadRequest {
	return &CreateFinancialCommitmentReportBadRequest{}
}

/*
CreateFinancialCommitmentReportBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type CreateFinancialCommitmentReportBadRequest struct {
	Payload *models.Errors
}

// IsSuccess returns true when this create financial commitment report bad request response has a 2xx status code
func (o *CreateFinancialCommitmentReportBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create financial commitment report bad request response has a 3xx status code
func (o *CreateFinancialCommitmentReportBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create financial commitment report bad request response has a 4xx status code
func (o *CreateFinancialCommitmentReportBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create financial commitment report bad request response has a 5xx status code
func (o *CreateFinancialCommitmentReportBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create financial commitment report bad request response a status code equal to that given
func (o *CreateFinancialCommitmentReportBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create financial commitment report bad request response
func (o *CreateFinancialCommitmentReportBadRequest) Code() int {
	return 400
}

func (o *CreateFinancialCommitmentReportBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportBadRequest %s", 400, payload)
}

func (o *CreateFinancialCommitmentReportBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportBadRequest %s", 400, payload)
}

func (o *CreateFinancialCommitmentReportBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateFinancialCommitmentReportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFinancialCommitmentReportUnprocessableEntity creates a CreateFinancialCommitmentReportUnprocessableEntity with default headers values
func NewCreateFinancialCommitmentReportUnprocessableEntity() *CreateFinancialCommitmentReportUnprocessableEntity {
	return &CreateFinancialCommitmentReportUnprocessableEntity{}
}

/*
CreateFinancialCommitmentReportUnprocessableEntity describes a response with status code 422, with default header values.

UnprocessableEntity
*/
type CreateFinancialCommitmentReportUnprocessableEntity struct {
	Payload *models.Errors
}

// IsSuccess returns true when this create financial commitment report unprocessable entity response has a 2xx status code
func (o *CreateFinancialCommitmentReportUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create financial commitment report unprocessable entity response has a 3xx status code
func (o *CreateFinancialCommitmentReportUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create financial commitment report unprocessable entity response has a 4xx status code
func (o *CreateFinancialCommitmentReportUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create financial commitment report unprocessable entity response has a 5xx status code
func (o *CreateFinancialCommitmentReportUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create financial commitment report unprocessable entity response a status code equal to that given
func (o *CreateFinancialCommitmentReportUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create financial commitment report unprocessable entity response
func (o *CreateFinancialCommitmentReportUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateFinancialCommitmentReportUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportUnprocessableEntity %s", 422, payload)
}

func (o *CreateFinancialCommitmentReportUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /financial_commitment_reports][%d] createFinancialCommitmentReportUnprocessableEntity %s", 422, payload)
}

func (o *CreateFinancialCommitmentReportUnprocessableEntity) GetPayload() *models.Errors {
	return o.Payload
}

func (o *CreateFinancialCommitmentReportUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
