// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AwsAccessCredential AwsAccessCredential model
//
// swagger:model AwsAccessCredential
type AwsAccessCredential struct {

	// bucket arn
	BucketArn string `json:"bucket_arn,omitempty"`

	// cross account arn
	// Required: true
	CrossAccountArn string `json:"cross_account_arn"`

	// id
	// Required: true
	ID int32 `json:"id"`
}

// Validate validates this aws access credential
func (m *AwsAccessCredential) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCrossAccountArn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AwsAccessCredential) validateCrossAccountArn(formats strfmt.Registry) error {

	if err := validate.RequiredString("cross_account_arn", "body", m.CrossAccountArn); err != nil {
		return err
	}

	return nil
}

func (m *AwsAccessCredential) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", int32(m.ID)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this aws access credential based on context it is used
func (m *AwsAccessCredential) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AwsAccessCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AwsAccessCredential) UnmarshalBinary(b []byte) error {
	var res AwsAccessCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
