// Code generated by go-swagger; DO NOT EDIT.

package cost_alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCostAlertParams creates a new DeleteCostAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCostAlertParams() *DeleteCostAlertParams {
	return &DeleteCostAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCostAlertParamsWithTimeout creates a new DeleteCostAlertParams object
// with the ability to set a timeout on a request.
func NewDeleteCostAlertParamsWithTimeout(timeout time.Duration) *DeleteCostAlertParams {
	return &DeleteCostAlertParams{
		timeout: timeout,
	}
}

// NewDeleteCostAlertParamsWithContext creates a new DeleteCostAlertParams object
// with the ability to set a context for a request.
func NewDeleteCostAlertParamsWithContext(ctx context.Context) *DeleteCostAlertParams {
	return &DeleteCostAlertParams{
		Context: ctx,
	}
}

// NewDeleteCostAlertParamsWithHTTPClient creates a new DeleteCostAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCostAlertParamsWithHTTPClient(client *http.Client) *DeleteCostAlertParams {
	return &DeleteCostAlertParams{
		HTTPClient: client,
	}
}

/*
DeleteCostAlertParams contains all the parameters to send to the API endpoint

	for the delete cost alert operation.

	Typically these are written to a http.Request.
*/
type DeleteCostAlertParams struct {

	/* CostAlertToken.

	   The token of the Cost Alert.
	*/
	CostAlertToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cost alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCostAlertParams) WithDefaults() *DeleteCostAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cost alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCostAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cost alert params
func (o *DeleteCostAlertParams) WithTimeout(timeout time.Duration) *DeleteCostAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cost alert params
func (o *DeleteCostAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cost alert params
func (o *DeleteCostAlertParams) WithContext(ctx context.Context) *DeleteCostAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cost alert params
func (o *DeleteCostAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cost alert params
func (o *DeleteCostAlertParams) WithHTTPClient(client *http.Client) *DeleteCostAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cost alert params
func (o *DeleteCostAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCostAlertToken adds the costAlertToken to the delete cost alert params
func (o *DeleteCostAlertParams) WithCostAlertToken(costAlertToken string) *DeleteCostAlertParams {
	o.SetCostAlertToken(costAlertToken)
	return o
}

// SetCostAlertToken adds the costAlertToken to the delete cost alert params
func (o *DeleteCostAlertParams) SetCostAlertToken(costAlertToken string) {
	o.CostAlertToken = costAlertToken
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCostAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cost_alert_token
	if err := r.SetPathParam("cost_alert_token", o.CostAlertToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
