// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetTagValuesReader is a Reader for the GetTagValues structure.
type GetTagValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTagValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTagValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTagValuesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tags/{key}/values] getTagValues", response, response.Code())
	}
}

// NewGetTagValuesOK creates a GetTagValuesOK with default headers values
func NewGetTagValuesOK() *GetTagValuesOK {
	return &GetTagValuesOK{}
}

/*
GetTagValuesOK describes a response with status code 200, with default header values.

GetTagValuesOK get tag values o k
*/
type GetTagValuesOK struct {
	Payload *models.TagValues
}

// IsSuccess returns true when this get tag values o k response has a 2xx status code
func (o *GetTagValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tag values o k response has a 3xx status code
func (o *GetTagValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tag values o k response has a 4xx status code
func (o *GetTagValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tag values o k response has a 5xx status code
func (o *GetTagValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tag values o k response a status code equal to that given
func (o *GetTagValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tag values o k response
func (o *GetTagValuesOK) Code() int {
	return 200
}

func (o *GetTagValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags/{key}/values][%d] getTagValuesOK %s", 200, payload)
}

func (o *GetTagValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags/{key}/values][%d] getTagValuesOK %s", 200, payload)
}

func (o *GetTagValuesOK) GetPayload() *models.TagValues {
	return o.Payload
}

func (o *GetTagValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagValues)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTagValuesNotFound creates a GetTagValuesNotFound with default headers values
func NewGetTagValuesNotFound() *GetTagValuesNotFound {
	return &GetTagValuesNotFound{}
}

/*
GetTagValuesNotFound describes a response with status code 404, with default header values.

NotFound
*/
type GetTagValuesNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get tag values not found response has a 2xx status code
func (o *GetTagValuesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tag values not found response has a 3xx status code
func (o *GetTagValuesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tag values not found response has a 4xx status code
func (o *GetTagValuesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get tag values not found response has a 5xx status code
func (o *GetTagValuesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get tag values not found response a status code equal to that given
func (o *GetTagValuesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get tag values not found response
func (o *GetTagValuesNotFound) Code() int {
	return 404
}

func (o *GetTagValuesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags/{key}/values][%d] getTagValuesNotFound %s", 404, payload)
}

func (o *GetTagValuesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tags/{key}/values][%d] getTagValuesNotFound %s", 404, payload)
}

func (o *GetTagValuesNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetTagValuesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
