// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev1/models"
)

// CreateIntegrationsAWSReader is a Reader for the CreateIntegrationsAWS structure.
type CreateIntegrationsAWSReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateIntegrationsAWSReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateIntegrationsAWSCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /integrations/aws] createIntegrationsAWS", response, response.Code())
	}
}

// NewCreateIntegrationsAWSCreated creates a CreateIntegrationsAWSCreated with default headers values
func NewCreateIntegrationsAWSCreated() *CreateIntegrationsAWSCreated {
	return &CreateIntegrationsAWSCreated{}
}

/*
CreateIntegrationsAWSCreated describes a response with status code 201, with default header values.

CreateIntegrationsAWSCreated create integrations a w s created
*/
type CreateIntegrationsAWSCreated struct {
	Payload *models.AwsAccessCredential
}

// IsSuccess returns true when this create integrations a w s created response has a 2xx status code
func (o *CreateIntegrationsAWSCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create integrations a w s created response has a 3xx status code
func (o *CreateIntegrationsAWSCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create integrations a w s created response has a 4xx status code
func (o *CreateIntegrationsAWSCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create integrations a w s created response has a 5xx status code
func (o *CreateIntegrationsAWSCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create integrations a w s created response a status code equal to that given
func (o *CreateIntegrationsAWSCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create integrations a w s created response
func (o *CreateIntegrationsAWSCreated) Code() int {
	return 201
}

func (o *CreateIntegrationsAWSCreated) Error() string {
	return fmt.Sprintf("[POST /integrations/aws][%d] createIntegrationsAWSCreated  %+v", 201, o.Payload)
}

func (o *CreateIntegrationsAWSCreated) String() string {
	return fmt.Sprintf("[POST /integrations/aws][%d] createIntegrationsAWSCreated  %+v", 201, o.Payload)
}

func (o *CreateIntegrationsAWSCreated) GetPayload() *models.AwsAccessCredential {
	return o.Payload
}

func (o *CreateIntegrationsAWSCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AwsAccessCredential)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
