// Code generated by go-swagger; DO NOT EDIT.

package virtual_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetVirtualTagConfigValueReader is a Reader for the GetVirtualTagConfigValue structure.
type GetVirtualTagConfigValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVirtualTagConfigValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVirtualTagConfigValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetVirtualTagConfigValueForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetVirtualTagConfigValueNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}] getVirtualTagConfigValue", response, response.Code())
	}
}

// NewGetVirtualTagConfigValueOK creates a GetVirtualTagConfigValueOK with default headers values
func NewGetVirtualTagConfigValueOK() *GetVirtualTagConfigValueOK {
	return &GetVirtualTagConfigValueOK{}
}

/*
GetVirtualTagConfigValueOK describes a response with status code 200, with default header values.

GetVirtualTagConfigValueOK get virtual tag config value o k
*/
type GetVirtualTagConfigValueOK struct {
	Payload *models.VirtualTagConfigValue
}

// IsSuccess returns true when this get virtual tag config value o k response has a 2xx status code
func (o *GetVirtualTagConfigValueOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get virtual tag config value o k response has a 3xx status code
func (o *GetVirtualTagConfigValueOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get virtual tag config value o k response has a 4xx status code
func (o *GetVirtualTagConfigValueOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get virtual tag config value o k response has a 5xx status code
func (o *GetVirtualTagConfigValueOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get virtual tag config value o k response a status code equal to that given
func (o *GetVirtualTagConfigValueOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get virtual tag config value o k response
func (o *GetVirtualTagConfigValueOK) Code() int {
	return 200
}

func (o *GetVirtualTagConfigValueOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueOK %s", 200, payload)
}

func (o *GetVirtualTagConfigValueOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueOK %s", 200, payload)
}

func (o *GetVirtualTagConfigValueOK) GetPayload() *models.VirtualTagConfigValue {
	return o.Payload
}

func (o *GetVirtualTagConfigValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualTagConfigValue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVirtualTagConfigValueForbidden creates a GetVirtualTagConfigValueForbidden with default headers values
func NewGetVirtualTagConfigValueForbidden() *GetVirtualTagConfigValueForbidden {
	return &GetVirtualTagConfigValueForbidden{}
}

/*
GetVirtualTagConfigValueForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetVirtualTagConfigValueForbidden struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get virtual tag config value forbidden response has a 2xx status code
func (o *GetVirtualTagConfigValueForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get virtual tag config value forbidden response has a 3xx status code
func (o *GetVirtualTagConfigValueForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get virtual tag config value forbidden response has a 4xx status code
func (o *GetVirtualTagConfigValueForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get virtual tag config value forbidden response has a 5xx status code
func (o *GetVirtualTagConfigValueForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get virtual tag config value forbidden response a status code equal to that given
func (o *GetVirtualTagConfigValueForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get virtual tag config value forbidden response
func (o *GetVirtualTagConfigValueForbidden) Code() int {
	return 403
}

func (o *GetVirtualTagConfigValueForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueForbidden %s", 403, payload)
}

func (o *GetVirtualTagConfigValueForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueForbidden %s", 403, payload)
}

func (o *GetVirtualTagConfigValueForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetVirtualTagConfigValueForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVirtualTagConfigValueNotFound creates a GetVirtualTagConfigValueNotFound with default headers values
func NewGetVirtualTagConfigValueNotFound() *GetVirtualTagConfigValueNotFound {
	return &GetVirtualTagConfigValueNotFound{}
}

/*
GetVirtualTagConfigValueNotFound describes a response with status code 404, with default header values.

NotFound
*/
type GetVirtualTagConfigValueNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get virtual tag config value not found response has a 2xx status code
func (o *GetVirtualTagConfigValueNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get virtual tag config value not found response has a 3xx status code
func (o *GetVirtualTagConfigValueNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get virtual tag config value not found response has a 4xx status code
func (o *GetVirtualTagConfigValueNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get virtual tag config value not found response has a 5xx status code
func (o *GetVirtualTagConfigValueNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get virtual tag config value not found response a status code equal to that given
func (o *GetVirtualTagConfigValueNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get virtual tag config value not found response
func (o *GetVirtualTagConfigValueNotFound) Code() int {
	return 404
}

func (o *GetVirtualTagConfigValueNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueNotFound %s", 404, payload)
}

func (o *GetVirtualTagConfigValueNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /virtual_tag_configs/{virtual_tag_config_token}/values/{virtual_tag_config_value_token}][%d] getVirtualTagConfigValueNotFound %s", 404, payload)
}

func (o *GetVirtualTagConfigValueNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetVirtualTagConfigValueNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
