// Code generated by go-swagger; DO NOT EDIT.

package virtual_tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetVirtualTagConfigReader is a Reader for the GetVirtualTagConfig structure.
type GetVirtualTagConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVirtualTagConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVirtualTagConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetVirtualTagConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /virtual_tag_configs/{token}] getVirtualTagConfig", response, response.Code())
	}
}

// NewGetVirtualTagConfigOK creates a GetVirtualTagConfigOK with default headers values
func NewGetVirtualTagConfigOK() *GetVirtualTagConfigOK {
	return &GetVirtualTagConfigOK{}
}

/*
GetVirtualTagConfigOK describes a response with status code 200, with default header values.

GetVirtualTagConfigOK get virtual tag config o k
*/
type GetVirtualTagConfigOK struct {
	Payload *models.VirtualTagConfig
}

// IsSuccess returns true when this get virtual tag config o k response has a 2xx status code
func (o *GetVirtualTagConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get virtual tag config o k response has a 3xx status code
func (o *GetVirtualTagConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get virtual tag config o k response has a 4xx status code
func (o *GetVirtualTagConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get virtual tag config o k response has a 5xx status code
func (o *GetVirtualTagConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get virtual tag config o k response a status code equal to that given
func (o *GetVirtualTagConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get virtual tag config o k response
func (o *GetVirtualTagConfigOK) Code() int {
	return 200
}

func (o *GetVirtualTagConfigOK) Error() string {
	return fmt.Sprintf("[GET /virtual_tag_configs/{token}][%d] getVirtualTagConfigOK  %+v", 200, o.Payload)
}

func (o *GetVirtualTagConfigOK) String() string {
	return fmt.Sprintf("[GET /virtual_tag_configs/{token}][%d] getVirtualTagConfigOK  %+v", 200, o.Payload)
}

func (o *GetVirtualTagConfigOK) GetPayload() *models.VirtualTagConfig {
	return o.Payload
}

func (o *GetVirtualTagConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualTagConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVirtualTagConfigNotFound creates a GetVirtualTagConfigNotFound with default headers values
func NewGetVirtualTagConfigNotFound() *GetVirtualTagConfigNotFound {
	return &GetVirtualTagConfigNotFound{}
}

/*
GetVirtualTagConfigNotFound describes a response with status code 404, with default header values.

NotFound
*/
type GetVirtualTagConfigNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get virtual tag config not found response has a 2xx status code
func (o *GetVirtualTagConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get virtual tag config not found response has a 3xx status code
func (o *GetVirtualTagConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get virtual tag config not found response has a 4xx status code
func (o *GetVirtualTagConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get virtual tag config not found response has a 5xx status code
func (o *GetVirtualTagConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get virtual tag config not found response a status code equal to that given
func (o *GetVirtualTagConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get virtual tag config not found response
func (o *GetVirtualTagConfigNotFound) Code() int {
	return 404
}

func (o *GetVirtualTagConfigNotFound) Error() string {
	return fmt.Sprintf("[GET /virtual_tag_configs/{token}][%d] getVirtualTagConfigNotFound  %+v", 404, o.Payload)
}

func (o *GetVirtualTagConfigNotFound) String() string {
	return fmt.Sprintf("[GET /virtual_tag_configs/{token}][%d] getVirtualTagConfigNotFound  %+v", 404, o.Payload)
}

func (o *GetVirtualTagConfigNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetVirtualTagConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
