// Code generated by go-swagger; DO NOT EDIT.

package access_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// DeleteAccessPolicyReader is a Reader for the DeleteAccessPolicy structure.
type DeleteAccessPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccessPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAccessPolicyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteAccessPolicyForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAccessPolicyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /access_policies/{access_policy_token}] deleteAccessPolicy", response, response.Code())
	}
}

// NewDeleteAccessPolicyNoContent creates a DeleteAccessPolicyNoContent with default headers values
func NewDeleteAccessPolicyNoContent() *DeleteAccessPolicyNoContent {
	return &DeleteAccessPolicyNoContent{}
}

/*
DeleteAccessPolicyNoContent describes a response with status code 204, with default header values.

DeleteAccessPolicyNoContent delete access policy no content
*/
type DeleteAccessPolicyNoContent struct {
	Payload *models.AccessPolicy
}

// IsSuccess returns true when this delete access policy no content response has a 2xx status code
func (o *DeleteAccessPolicyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete access policy no content response has a 3xx status code
func (o *DeleteAccessPolicyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access policy no content response has a 4xx status code
func (o *DeleteAccessPolicyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete access policy no content response has a 5xx status code
func (o *DeleteAccessPolicyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access policy no content response a status code equal to that given
func (o *DeleteAccessPolicyNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete access policy no content response
func (o *DeleteAccessPolicyNoContent) Code() int {
	return 204
}

func (o *DeleteAccessPolicyNoContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyNoContent %s", 204, payload)
}

func (o *DeleteAccessPolicyNoContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyNoContent %s", 204, payload)
}

func (o *DeleteAccessPolicyNoContent) GetPayload() *models.AccessPolicy {
	return o.Payload
}

func (o *DeleteAccessPolicyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessPolicyForbidden creates a DeleteAccessPolicyForbidden with default headers values
func NewDeleteAccessPolicyForbidden() *DeleteAccessPolicyForbidden {
	return &DeleteAccessPolicyForbidden{}
}

/*
DeleteAccessPolicyForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteAccessPolicyForbidden struct {
	Payload *models.Errors
}

// IsSuccess returns true when this delete access policy forbidden response has a 2xx status code
func (o *DeleteAccessPolicyForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access policy forbidden response has a 3xx status code
func (o *DeleteAccessPolicyForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access policy forbidden response has a 4xx status code
func (o *DeleteAccessPolicyForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access policy forbidden response has a 5xx status code
func (o *DeleteAccessPolicyForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access policy forbidden response a status code equal to that given
func (o *DeleteAccessPolicyForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete access policy forbidden response
func (o *DeleteAccessPolicyForbidden) Code() int {
	return 403
}

func (o *DeleteAccessPolicyForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyForbidden %s", 403, payload)
}

func (o *DeleteAccessPolicyForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyForbidden %s", 403, payload)
}

func (o *DeleteAccessPolicyForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *DeleteAccessPolicyForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccessPolicyNotFound creates a DeleteAccessPolicyNotFound with default headers values
func NewDeleteAccessPolicyNotFound() *DeleteAccessPolicyNotFound {
	return &DeleteAccessPolicyNotFound{}
}

/*
DeleteAccessPolicyNotFound describes a response with status code 404, with default header values.

NotFound
*/
type DeleteAccessPolicyNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this delete access policy not found response has a 2xx status code
func (o *DeleteAccessPolicyNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete access policy not found response has a 3xx status code
func (o *DeleteAccessPolicyNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete access policy not found response has a 4xx status code
func (o *DeleteAccessPolicyNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete access policy not found response has a 5xx status code
func (o *DeleteAccessPolicyNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete access policy not found response a status code equal to that given
func (o *DeleteAccessPolicyNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete access policy not found response
func (o *DeleteAccessPolicyNotFound) Code() int {
	return 404
}

func (o *DeleteAccessPolicyNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyNotFound %s", 404, payload)
}

func (o *DeleteAccessPolicyNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /access_policies/{access_policy_token}][%d] deleteAccessPolicyNotFound %s", 404, payload)
}

func (o *DeleteAccessPolicyNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *DeleteAccessPolicyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
