// Code generated by go-swagger; DO NOT EDIT.

package access_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAccessPolicyParams creates a new DeleteAccessPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAccessPolicyParams() *DeleteAccessPolicyParams {
	return &DeleteAccessPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccessPolicyParamsWithTimeout creates a new DeleteAccessPolicyParams object
// with the ability to set a timeout on a request.
func NewDeleteAccessPolicyParamsWithTimeout(timeout time.Duration) *DeleteAccessPolicyParams {
	return &DeleteAccessPolicyParams{
		timeout: timeout,
	}
}

// NewDeleteAccessPolicyParamsWithContext creates a new DeleteAccessPolicyParams object
// with the ability to set a context for a request.
func NewDeleteAccessPolicyParamsWithContext(ctx context.Context) *DeleteAccessPolicyParams {
	return &DeleteAccessPolicyParams{
		Context: ctx,
	}
}

// NewDeleteAccessPolicyParamsWithHTTPClient creates a new DeleteAccessPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAccessPolicyParamsWithHTTPClient(client *http.Client) *DeleteAccessPolicyParams {
	return &DeleteAccessPolicyParams{
		HTTPClient: client,
	}
}

/*
DeleteAccessPolicyParams contains all the parameters to send to the API endpoint

	for the delete access policy operation.

	Typically these are written to a http.Request.
*/
type DeleteAccessPolicyParams struct {

	// AccessPolicyToken.
	AccessPolicyToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete access policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessPolicyParams) WithDefaults() *DeleteAccessPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete access policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAccessPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete access policy params
func (o *DeleteAccessPolicyParams) WithTimeout(timeout time.Duration) *DeleteAccessPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete access policy params
func (o *DeleteAccessPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete access policy params
func (o *DeleteAccessPolicyParams) WithContext(ctx context.Context) *DeleteAccessPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete access policy params
func (o *DeleteAccessPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete access policy params
func (o *DeleteAccessPolicyParams) WithHTTPClient(client *http.Client) *DeleteAccessPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete access policy params
func (o *DeleteAccessPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessPolicyToken adds the accessPolicyToken to the delete access policy params
func (o *DeleteAccessPolicyParams) WithAccessPolicyToken(accessPolicyToken string) *DeleteAccessPolicyParams {
	o.SetAccessPolicyToken(accessPolicyToken)
	return o
}

// SetAccessPolicyToken adds the accessPolicyToken to the delete access policy params
func (o *DeleteAccessPolicyParams) SetAccessPolicyToken(accessPolicyToken string) {
	o.AccessPolicyToken = accessPolicyToken
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccessPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param access_policy_token
	if err := r.SetPathParam("access_policy_token", o.AccessPolicyToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
