// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdjustmentItem adjustment item
//
// swagger:model AdjustmentItem
type AdjustmentItem struct {

	// Type of adjustment
	// Required: true
	// Enum: ["charge","credit","discount"]
	AdjustmentType string `json:"adjustment_type"`

	// Amount or percentage value for the adjustment
	// Required: true
	Amount string `json:"amount"`

	// How the adjustment is calculated
	// Required: true
	// Enum: ["fixed","percentage"]
	CalculationType string `json:"calculation_type"`

	// Name of the adjustment (e.g., 'State Tax', 'Processing Fee')
	// Required: true
	Name string `json:"name"`
}

// Validate validates this adjustment item
func (m *AdjustmentItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdjustmentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCalculationType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var adjustmentItemTypeAdjustmentTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["charge","credit","discount"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		adjustmentItemTypeAdjustmentTypePropEnum = append(adjustmentItemTypeAdjustmentTypePropEnum, v)
	}
}

const (

	// AdjustmentItemAdjustmentTypeCharge captures enum value "charge"
	AdjustmentItemAdjustmentTypeCharge string = "charge"

	// AdjustmentItemAdjustmentTypeCredit captures enum value "credit"
	AdjustmentItemAdjustmentTypeCredit string = "credit"

	// AdjustmentItemAdjustmentTypeDiscount captures enum value "discount"
	AdjustmentItemAdjustmentTypeDiscount string = "discount"
)

// prop value enum
func (m *AdjustmentItem) validateAdjustmentTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, adjustmentItemTypeAdjustmentTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AdjustmentItem) validateAdjustmentType(formats strfmt.Registry) error {

	if err := validate.RequiredString("adjustment_type", "body", m.AdjustmentType); err != nil {
		return err
	}

	// value enum
	if err := m.validateAdjustmentTypeEnum("adjustment_type", "body", m.AdjustmentType); err != nil {
		return err
	}

	return nil
}

func (m *AdjustmentItem) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

var adjustmentItemTypeCalculationTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["fixed","percentage"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		adjustmentItemTypeCalculationTypePropEnum = append(adjustmentItemTypeCalculationTypePropEnum, v)
	}
}

const (

	// AdjustmentItemCalculationTypeFixed captures enum value "fixed"
	AdjustmentItemCalculationTypeFixed string = "fixed"

	// AdjustmentItemCalculationTypePercentage captures enum value "percentage"
	AdjustmentItemCalculationTypePercentage string = "percentage"
)

// prop value enum
func (m *AdjustmentItem) validateCalculationTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, adjustmentItemTypeCalculationTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AdjustmentItem) validateCalculationType(formats strfmt.Registry) error {

	if err := validate.RequiredString("calculation_type", "body", m.CalculationType); err != nil {
		return err
	}

	// value enum
	if err := m.validateCalculationTypeEnum("calculation_type", "body", m.CalculationType); err != nil {
		return err
	}

	return nil
}

func (m *AdjustmentItem) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this adjustment item based on context it is used
func (m *AdjustmentItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdjustmentItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdjustmentItem) UnmarshalBinary(b []byte) error {
	var res AdjustmentItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
