// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BudgetPeriod budget period
//
// swagger:model BudgetPeriod
type BudgetPeriod struct {

	// The amount of the Budget Period as a string to ensure precision.
	// Example: 100.00
	// Required: true
	Amount string `json:"amount"`

	// The date and time, in UTC, the Budget was created. ISO 8601 Formatted.
	// Example: 2024-03-19T00:00:00Z
	// Required: true
	EndAt string `json:"end_at"`

	// The date and time, in UTC, the Budget was created. ISO 8601 Formatted.
	// Example: 2024-03-19T00:00:00Z
	// Required: true
	StartAt string `json:"start_at"`
}

// Validate validates this budget period
func (m *BudgetPeriod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BudgetPeriod) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *BudgetPeriod) validateEndAt(formats strfmt.Registry) error {

	if err := validate.RequiredString("end_at", "body", m.EndAt); err != nil {
		return err
	}

	return nil
}

func (m *BudgetPeriod) validateStartAt(formats strfmt.Registry) error {

	if err := validate.RequiredString("start_at", "body", m.StartAt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this budget period based on context it is used
func (m *BudgetPeriod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BudgetPeriod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BudgetPeriod) UnmarshalBinary(b []byte) error {
	var res BudgetPeriod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
