// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BusinessMetric BusinessMetric model
//
// swagger:model BusinessMetric
type BusinessMetric struct {

	// The title of the Business Metric.
	// Example: Total Revenue
	Title string `json:"title,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this business metric
func (m *BusinessMetric) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this business metric based on context it is used
func (m *BusinessMetric) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BusinessMetric) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BusinessMetric) UnmarshalBinary(b []byte) error {
	var res BusinessMetric
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
