// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CostProviders CostProviders model
//
// swagger:model CostProviders
type CostProviders struct {

	// cost providers
	CostProviders []*CostProvider `json:"cost_providers"`

	// links
	Links interface{} `json:"links,omitempty"`
}

// Validate validates this cost providers
func (m *CostProviders) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCostProviders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostProviders) validateCostProviders(formats strfmt.Registry) error {
	if swag.IsZero(m.CostProviders) { // not required
		return nil
	}

	for i := 0; i < len(m.CostProviders); i++ {
		if swag.IsZero(m.CostProviders[i]) { // not required
			continue
		}

		if m.CostProviders[i] != nil {
			if err := m.CostProviders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cost_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cost_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this cost providers based on the context it is used
func (m *CostProviders) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCostProviders(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CostProviders) contextValidateCostProviders(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CostProviders); i++ {

		if m.CostProviders[i] != nil {

			if swag.IsZero(m.CostProviders[i]) { // not required
				return nil
			}

			if err := m.CostProviders[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cost_providers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cost_providers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CostProviders) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CostProviders) UnmarshalBinary(b []byte) error {
	var res CostProviders
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
