// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCostExport Generate a DataExport of costs.
//
// swagger:model createCostExport
type CreateCostExport struct {

	// The CostReport token.
	CostReportToken string `json:"cost_report_token,omitempty"`

	// The date bin of the costs. Defaults to the report's default or day.
	// Enum: ["day","week","month","quarter","hour"]
	DateBin string `json:"date_bin,omitempty"`

	// Last date you would like to filter costs to. ISO 8601 formatted.
	EndDate string `json:"end_date,omitempty"`

	// The VQL filter to apply to the costs. If this is supplied you do not need cost_report_token.
	Filter string `json:"filter,omitempty"`

	// Group the results by specific field(s). Defaults to provider, service, account_id. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region
	Groupings []string `json:"groupings"`

	// The schema of the data export.
	// Enum: ["vntg","focus","comparison"]
	Schema *string `json:"schema,omitempty"`

	// settings
	Settings *CreateCostExportSettings `json:"settings,omitempty"`

	// First date you would like to filter costs from. ISO 8601 formatted.
	StartDate string `json:"start_date,omitempty"`

	// The token of the Workspace to query costs from. Ignored if 'cost_report_token' is set. Required if the API token is associated with multiple Workspaces.
	WorkspaceToken string `json:"workspace_token,omitempty"`
}

// Validate validates this create cost export
func (m *CreateCostExport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateBin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchema(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSettings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createCostExportTypeDateBinPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["day","week","month","quarter","hour"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCostExportTypeDateBinPropEnum = append(createCostExportTypeDateBinPropEnum, v)
	}
}

const (

	// CreateCostExportDateBinDay captures enum value "day"
	CreateCostExportDateBinDay string = "day"

	// CreateCostExportDateBinWeek captures enum value "week"
	CreateCostExportDateBinWeek string = "week"

	// CreateCostExportDateBinMonth captures enum value "month"
	CreateCostExportDateBinMonth string = "month"

	// CreateCostExportDateBinQuarter captures enum value "quarter"
	CreateCostExportDateBinQuarter string = "quarter"

	// CreateCostExportDateBinHour captures enum value "hour"
	CreateCostExportDateBinHour string = "hour"
)

// prop value enum
func (m *CreateCostExport) validateDateBinEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createCostExportTypeDateBinPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateCostExport) validateDateBin(formats strfmt.Registry) error {
	if swag.IsZero(m.DateBin) { // not required
		return nil
	}

	// value enum
	if err := m.validateDateBinEnum("date_bin", "body", m.DateBin); err != nil {
		return err
	}

	return nil
}

var createCostExportTypeSchemaPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["vntg","focus","comparison"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCostExportTypeSchemaPropEnum = append(createCostExportTypeSchemaPropEnum, v)
	}
}

const (

	// CreateCostExportSchemaVntg captures enum value "vntg"
	CreateCostExportSchemaVntg string = "vntg"

	// CreateCostExportSchemaFocus captures enum value "focus"
	CreateCostExportSchemaFocus string = "focus"

	// CreateCostExportSchemaComparison captures enum value "comparison"
	CreateCostExportSchemaComparison string = "comparison"
)

// prop value enum
func (m *CreateCostExport) validateSchemaEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createCostExportTypeSchemaPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateCostExport) validateSchema(formats strfmt.Registry) error {
	if swag.IsZero(m.Schema) { // not required
		return nil
	}

	// value enum
	if err := m.validateSchemaEnum("schema", "body", *m.Schema); err != nil {
		return err
	}

	return nil
}

func (m *CreateCostExport) validateSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.Settings) { // not required
		return nil
	}

	if m.Settings != nil {
		if err := m.Settings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("settings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("settings")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create cost export based on the context it is used
func (m *CreateCostExport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateCostExport) contextValidateSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.Settings != nil {

		if swag.IsZero(m.Settings) { // not required
			return nil
		}

		if err := m.Settings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("settings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("settings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateCostExport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCostExport) UnmarshalBinary(b []byte) error {
	var res CreateCostExport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateCostExportSettings Cost-related settings.
//
// swagger:model CreateCostExportSettings
type CreateCostExportSettings struct {

	// Results will aggregate by cost or usage.
	AggregateBy *string `json:"aggregate_by,omitempty"`

	// Results will amortize.
	Amortize *bool `json:"amortize,omitempty"`

	// Results will include credits.
	IncludeCredits *bool `json:"include_credits,omitempty"`

	// Results will include discounts.
	IncludeDiscounts *bool `json:"include_discounts,omitempty"`

	// Results will include refunds.
	IncludeRefunds *bool `json:"include_refunds,omitempty"`

	// Results will include tax.
	IncludeTax *bool `json:"include_tax,omitempty"`

	// Results will show previous period costs or usage comparison.
	ShowPreviousPeriod *bool `json:"show_previous_period,omitempty"`

	// Results will show unallocated costs.
	Unallocated *bool `json:"unallocated,omitempty"`
}

// Validate validates this create cost export settings
func (m *CreateCostExportSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create cost export settings based on context it is used
func (m *CreateCostExportSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateCostExportSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCostExportSettings) UnmarshalBinary(b []byte) error {
	var res CreateCostExportSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
