// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCustomProviderIntegration Create a Custom Provider Integration
//
// swagger:model createCustomProviderIntegration
type CreateCustomProviderIntegration struct {

	// Description of the Custom Provider Integration.
	Description string `json:"description,omitempty"`

	// Name of the Custom Provider Integration.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this create custom provider integration
func (m *CreateCustomProviderIntegration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateCustomProviderIntegration) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create custom provider integration based on context it is used
func (m *CreateCustomProviderIntegration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateCustomProviderIntegration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCustomProviderIntegration) UnmarshalBinary(b []byte) error {
	var res CreateCustomProviderIntegration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
