// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateVirtualTagConfigValue Create a VirtualTagConfigValue.
//
// swagger:model createVirtualTagConfigValue
type CreateVirtualTagConfigValue struct {

	// The token of an associated business metric.
	BusinessMetricToken string `json:"business_metric_token,omitempty"`

	// cost metric
	CostMetric *CreateVirtualTagConfigValueCostMetric `json:"cost_metric,omitempty"`

	// Date ranges restricting when this value applies.
	DateRanges []*CreateVirtualTagConfigValueDateRangesItems0 `json:"date_ranges,omitempty"`

	// The display name for a cost metric or percentage allocation value.
	DisplayName *string `json:"display_name,omitempty"`

	// The filter query language to apply to the value. Additional documentation available at https://docs.vantage.sh/vql.
	// Required: true
	Filter *string `json:"filter"`

	// The business metric label key used for this virtual tag value.
	LabelKey string `json:"label_key,omitempty"`

	// label transforms
	LabelTransforms []*CreateVirtualTagConfigValueLabelTransformsItems0 `json:"label_transforms,omitempty"`

	// Business metric label values. An empty array includes every value for the label key.
	LabelValues []string `json:"label_values,omitempty"`

	// The name of the value.
	Name string `json:"name,omitempty"`

	// percentages
	Percentages []*CreateVirtualTagConfigValuePercentagesItems0 `json:"percentages,omitempty"`
}

// Validate validates this create virtual tag config value
func (m *CreateVirtualTagConfigValue) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCostMetric(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateRanges(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabelTransforms(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePercentages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValue) validateCostMetric(formats strfmt.Registry) error {
	if swag.IsZero(m.CostMetric) { // not required
		return nil
	}

	if m.CostMetric != nil {
		if err := m.CostMetric.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost_metric")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost_metric")
			}
			return err
		}
	}

	return nil
}

func (m *CreateVirtualTagConfigValue) validateDateRanges(formats strfmt.Registry) error {
	if swag.IsZero(m.DateRanges) { // not required
		return nil
	}

	for i := 0; i < len(m.DateRanges); i++ {
		if swag.IsZero(m.DateRanges[i]) { // not required
			continue
		}

		if m.DateRanges[i] != nil {
			if err := m.DateRanges[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("date_ranges" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("date_ranges" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateVirtualTagConfigValue) validateFilter(formats strfmt.Registry) error {

	if err := validate.Required("filter", "body", m.Filter); err != nil {
		return err
	}

	return nil
}

func (m *CreateVirtualTagConfigValue) validateLabelTransforms(formats strfmt.Registry) error {
	if swag.IsZero(m.LabelTransforms) { // not required
		return nil
	}

	for i := 0; i < len(m.LabelTransforms); i++ {
		if swag.IsZero(m.LabelTransforms[i]) { // not required
			continue
		}

		if m.LabelTransforms[i] != nil {
			if err := m.LabelTransforms[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("label_transforms" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("label_transforms" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateVirtualTagConfigValue) validatePercentages(formats strfmt.Registry) error {
	if swag.IsZero(m.Percentages) { // not required
		return nil
	}

	for i := 0; i < len(m.Percentages); i++ {
		if swag.IsZero(m.Percentages[i]) { // not required
			continue
		}

		if m.Percentages[i] != nil {
			if err := m.Percentages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("percentages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("percentages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this create virtual tag config value based on the context it is used
func (m *CreateVirtualTagConfigValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCostMetric(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDateRanges(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLabelTransforms(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePercentages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValue) contextValidateCostMetric(ctx context.Context, formats strfmt.Registry) error {

	if m.CostMetric != nil {

		if swag.IsZero(m.CostMetric) { // not required
			return nil
		}

		if err := m.CostMetric.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost_metric")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost_metric")
			}
			return err
		}
	}

	return nil
}

func (m *CreateVirtualTagConfigValue) contextValidateDateRanges(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DateRanges); i++ {

		if m.DateRanges[i] != nil {

			if swag.IsZero(m.DateRanges[i]) { // not required
				return nil
			}

			if err := m.DateRanges[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("date_ranges" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("date_ranges" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateVirtualTagConfigValue) contextValidateLabelTransforms(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.LabelTransforms); i++ {

		if m.LabelTransforms[i] != nil {

			if swag.IsZero(m.LabelTransforms[i]) { // not required
				return nil
			}

			if err := m.LabelTransforms[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("label_transforms" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("label_transforms" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CreateVirtualTagConfigValue) contextValidatePercentages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Percentages); i++ {

		if m.Percentages[i] != nil {

			if swag.IsZero(m.Percentages[i]) { // not required
				return nil
			}

			if err := m.Percentages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("percentages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("percentages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValue) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateVirtualTagConfigValueCostMetric create virtual tag config value cost metric
//
// swagger:model CreateVirtualTagConfigValueCostMetric
type CreateVirtualTagConfigValueCostMetric struct {

	// aggregation
	// Required: true
	Aggregation *CreateVirtualTagConfigValueCostMetricAggregation `json:"aggregation"`

	// filter
	// Required: true
	Filter *string `json:"filter"`
}

// Validate validates this create virtual tag config value cost metric
func (m *CreateVirtualTagConfigValueCostMetric) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAggregation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValueCostMetric) validateAggregation(formats strfmt.Registry) error {

	if err := validate.Required("cost_metric"+"."+"aggregation", "body", m.Aggregation); err != nil {
		return err
	}

	if m.Aggregation != nil {
		if err := m.Aggregation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost_metric" + "." + "aggregation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost_metric" + "." + "aggregation")
			}
			return err
		}
	}

	return nil
}

func (m *CreateVirtualTagConfigValueCostMetric) validateFilter(formats strfmt.Registry) error {

	if err := validate.Required("cost_metric"+"."+"filter", "body", m.Filter); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create virtual tag config value cost metric based on the context it is used
func (m *CreateVirtualTagConfigValueCostMetric) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAggregation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValueCostMetric) contextValidateAggregation(ctx context.Context, formats strfmt.Registry) error {

	if m.Aggregation != nil {

		if err := m.Aggregation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cost_metric" + "." + "aggregation")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cost_metric" + "." + "aggregation")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueCostMetric) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueCostMetric) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValueCostMetric
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateVirtualTagConfigValueCostMetricAggregation create virtual tag config value cost metric aggregation
//
// swagger:model CreateVirtualTagConfigValueCostMetricAggregation
type CreateVirtualTagConfigValueCostMetricAggregation struct {

	// tag
	// Required: true
	Tag *string `json:"tag"`
}

// Validate validates this create virtual tag config value cost metric aggregation
func (m *CreateVirtualTagConfigValueCostMetricAggregation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTag(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValueCostMetricAggregation) validateTag(formats strfmt.Registry) error {

	if err := validate.Required("cost_metric"+"."+"aggregation"+"."+"tag", "body", m.Tag); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create virtual tag config value cost metric aggregation based on context it is used
func (m *CreateVirtualTagConfigValueCostMetricAggregation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueCostMetricAggregation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueCostMetricAggregation) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValueCostMetricAggregation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateVirtualTagConfigValueDateRangesItems0 create virtual tag config value date ranges items0
//
// swagger:model CreateVirtualTagConfigValueDateRangesItems0
type CreateVirtualTagConfigValueDateRangesItems0 struct {

	// end date
	EndDate *string `json:"end_date,omitempty"`

	// start date
	StartDate *string `json:"start_date,omitempty"`
}

// Validate validates this create virtual tag config value date ranges items0
func (m *CreateVirtualTagConfigValueDateRangesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create virtual tag config value date ranges items0 based on context it is used
func (m *CreateVirtualTagConfigValueDateRangesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueDateRangesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueDateRangesItems0) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValueDateRangesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateVirtualTagConfigValueLabelTransformsItems0 create virtual tag config value label transforms items0
//
// swagger:model CreateVirtualTagConfigValueLabelTransformsItems0
type CreateVirtualTagConfigValueLabelTransformsItems0 struct {

	// delimiter
	Delimiter *string `json:"delimiter,omitempty"`

	// index
	Index *int32 `json:"index,omitempty"`

	// template
	Template *string `json:"template,omitempty"`

	// type
	// Required: true
	// Enum: ["split","format"]
	Type *string `json:"type"`
}

// Validate validates this create virtual tag config value label transforms items0
func (m *CreateVirtualTagConfigValueLabelTransformsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createVirtualTagConfigValueLabelTransformsItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["split","format"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createVirtualTagConfigValueLabelTransformsItems0TypeTypePropEnum = append(createVirtualTagConfigValueLabelTransformsItems0TypeTypePropEnum, v)
	}
}

const (

	// CreateVirtualTagConfigValueLabelTransformsItems0TypeSplit captures enum value "split"
	CreateVirtualTagConfigValueLabelTransformsItems0TypeSplit string = "split"

	// CreateVirtualTagConfigValueLabelTransformsItems0TypeFormat captures enum value "format"
	CreateVirtualTagConfigValueLabelTransformsItems0TypeFormat string = "format"
)

// prop value enum
func (m *CreateVirtualTagConfigValueLabelTransformsItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createVirtualTagConfigValueLabelTransformsItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateVirtualTagConfigValueLabelTransformsItems0) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create virtual tag config value label transforms items0 based on context it is used
func (m *CreateVirtualTagConfigValueLabelTransformsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueLabelTransformsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValueLabelTransformsItems0) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValueLabelTransformsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateVirtualTagConfigValuePercentagesItems0 create virtual tag config value percentages items0
//
// swagger:model CreateVirtualTagConfigValuePercentagesItems0
type CreateVirtualTagConfigValuePercentagesItems0 struct {

	// pct
	// Required: true
	Pct *float32 `json:"pct"`

	// value
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this create virtual tag config value percentages items0
func (m *CreateVirtualTagConfigValuePercentagesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePct(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVirtualTagConfigValuePercentagesItems0) validatePct(formats strfmt.Registry) error {

	if err := validate.Required("pct", "body", m.Pct); err != nil {
		return err
	}

	return nil
}

func (m *CreateVirtualTagConfigValuePercentagesItems0) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create virtual tag config value percentages items0 based on context it is used
func (m *CreateVirtualTagConfigValuePercentagesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVirtualTagConfigValuePercentagesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVirtualTagConfigValuePercentagesItems0) UnmarshalBinary(b []byte) error {
	var res CreateVirtualTagConfigValuePercentagesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
