// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateResourceReport Create a ResourceReport.
//
// swagger:model createResourceReport
type CreateResourceReport struct {

	// The VQL filter for the ResourceReport.
	Filter string `json:"filter,omitempty"`

	// The title of the ResourceReport.
	Title string `json:"title,omitempty"`

	// The token of the Workspace to add the ResourceReport to.
	// Required: true
	WorkspaceToken *string `json:"workspace_token"`
}

// Validate validates this create resource report
func (m *CreateResourceReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkspaceToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateResourceReport) validateWorkspaceToken(formats strfmt.Registry) error {

	if err := validate.Required("workspace_token", "body", m.WorkspaceToken); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create resource report based on context it is used
func (m *CreateResourceReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateResourceReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateResourceReport) UnmarshalBinary(b []byte) error {
	var res CreateResourceReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
