// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DefaultForecast default forecast
//
// swagger:model DefaultForecast
type DefaultForecast struct {

	// The default forecast selection kind.
	// Required: true
	// Enum: ["baseline","report_forecast"]
	Kind string `json:"kind"`

	// The token for the report forecast selected as the default.
	ReportForecastToken *string `json:"report_forecast_token,omitempty"`
}

// Validate validates this default forecast
func (m *DefaultForecast) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var defaultForecastTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["baseline","report_forecast"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		defaultForecastTypeKindPropEnum = append(defaultForecastTypeKindPropEnum, v)
	}
}

const (

	// DefaultForecastKindBaseline captures enum value "baseline"
	DefaultForecastKindBaseline string = "baseline"

	// DefaultForecastKindReportForecast captures enum value "report_forecast"
	DefaultForecastKindReportForecast string = "report_forecast"
)

// prop value enum
func (m *DefaultForecast) validateKindEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, defaultForecastTypeKindPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DefaultForecast) validateKind(formats strfmt.Registry) error {

	if err := validate.RequiredString("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", m.Kind); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this default forecast based on context it is used
func (m *DefaultForecast) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefaultForecast) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefaultForecast) UnmarshalBinary(b []byte) error {
	var res DefaultForecast
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
