// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExchangeRate exchange rate
//
// swagger:model exchange_rate
type ExchangeRate struct {

	// base currency code
	// Required: true
	BaseCurrencyCode *string `json:"base_currency_code"`

	// currency code
	// Required: true
	CurrencyCode *string `json:"currency_code"`

	// effective date
	// Required: true
	EffectiveDate *string `json:"effective_date"`

	// rate
	// Required: true
	Rate *string `json:"rate"`

	// updated at
	// Required: true
	UpdatedAt *string `json:"updated_at"`
}

// Validate validates this exchange rate
func (m *ExchangeRate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseCurrencyCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrencyCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEffectiveDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExchangeRate) validateBaseCurrencyCode(formats strfmt.Registry) error {

	if err := validate.Required("base_currency_code", "body", m.BaseCurrencyCode); err != nil {
		return err
	}

	return nil
}

func (m *ExchangeRate) validateCurrencyCode(formats strfmt.Registry) error {

	if err := validate.Required("currency_code", "body", m.CurrencyCode); err != nil {
		return err
	}

	return nil
}

func (m *ExchangeRate) validateEffectiveDate(formats strfmt.Registry) error {

	if err := validate.Required("effective_date", "body", m.EffectiveDate); err != nil {
		return err
	}

	return nil
}

func (m *ExchangeRate) validateRate(formats strfmt.Registry) error {

	if err := validate.Required("rate", "body", m.Rate); err != nil {
		return err
	}

	return nil
}

func (m *ExchangeRate) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this exchange rate based on context it is used
func (m *ExchangeRate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExchangeRate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExchangeRate) UnmarshalBinary(b []byte) error {
	var res ExchangeRate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
