// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FinancialCommitmentReportCost financial commitment report cost
//
// swagger:model FinancialCommitmentReportCost
type FinancialCommitmentReportCost struct {

	// The date the cost was accrued. ISO 8601 Formatted.
	// Example: 2024-03-01T00:00:00Z
	// Required: true
	AccruedAt string `json:"accrued_at"`

	// The net (discounted) cost amount.
	// Example: 100.00
	// Required: true
	Amount string `json:"amount"`

	// The identifier of the financial commitment.
	// Example: sp-1234567890abcdef0
	CommitmentID *string `json:"commitment_id,omitempty"`

	// The type of financial commitment.
	// Example: savings_plan
	CommitmentType *string `json:"commitment_type,omitempty"`

	// The category for the cost.
	// Example: Data Transfer
	CostCategory *string `json:"cost_category,omitempty"`

	// The subcategory for the cost.
	// Example: DataTransfer-Regional-Bytes
	CostSubCategory *string `json:"cost_sub_category,omitempty"`

	// The type of cost.
	// Example: SavingsPlanCoveredUsage
	CostType *string `json:"cost_type,omitempty"`

	// The gross amount of costs covered by commitments.
	// Example: 100.00
	// Required: true
	CoveredGrossAmount string `json:"covered_gross_amount"`

	// The currency of the cost.
	// Example: USD
	// Required: true
	Currency string `json:"currency"`

	// The gross cost amount before discounts.
	// Example: 150.00
	// Required: true
	GrossAmount string `json:"gross_amount"`

	// The instance type which incurred the cost.
	// Example: m5.xlarge
	InstanceType *string `json:"instance_type,omitempty"`

	// The on-demand usage cost amount.
	// Example: 50.00
	// Required: true
	OnDemandAmount string `json:"on_demand_amount"`

	// The billing account ID which incurred the cost.
	// Example: 123456789012
	ProviderAccountID *string `json:"provider_account_id,omitempty"`

	// The region which incurred the cost.
	// Example: us-east-1
	Region *string `json:"region,omitempty"`

	// The resource account ID which incurred the cost.
	// Example: 123456789012
	ResourceAccountID *string `json:"resource_account_id,omitempty"`

	// The service which incurred the cost.
	// Example: Amazon Elastic Compute Cloud - Compute
	Service *string `json:"service,omitempty"`

	// The tag key/value pairs attached to the cost that was incurred.
	Tags []*FinancialCommitmentReportCostTag `json:"tags"`
}

// Validate validates this financial commitment report cost
func (m *FinancialCommitmentReportCost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccruedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCoveredGrossAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGrossAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnDemandAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FinancialCommitmentReportCost) validateAccruedAt(formats strfmt.Registry) error {

	if err := validate.RequiredString("accrued_at", "body", m.AccruedAt); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateCoveredGrossAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("covered_gross_amount", "body", m.CoveredGrossAmount); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateCurrency(formats strfmt.Registry) error {

	if err := validate.RequiredString("currency", "body", m.Currency); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateGrossAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("gross_amount", "body", m.GrossAmount); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateOnDemandAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("on_demand_amount", "body", m.OnDemandAmount); err != nil {
		return err
	}

	return nil
}

func (m *FinancialCommitmentReportCost) validateTags(formats strfmt.Registry) error {
	if swag.IsZero(m.Tags) { // not required
		return nil
	}

	for i := 0; i < len(m.Tags); i++ {
		if swag.IsZero(m.Tags[i]) { // not required
			continue
		}

		if m.Tags[i] != nil {
			if err := m.Tags[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this financial commitment report cost based on the context it is used
func (m *FinancialCommitmentReportCost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTags(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FinancialCommitmentReportCost) contextValidateTags(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tags); i++ {

		if m.Tags[i] != nil {

			if swag.IsZero(m.Tags[i]) { // not required
				return nil
			}

			if err := m.Tags[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tags" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tags" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FinancialCommitmentReportCost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FinancialCommitmentReportCost) UnmarshalBinary(b []byte) error {
	var res FinancialCommitmentReportCost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
