// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KubernetesEfficiencyReport KubernetesEfficiencyReport model
//
// swagger:model KubernetesEfficiencyReport
type KubernetesEfficiencyReport struct {

	// How costs are aggregated by. Possible values: idle_costs, amount.
	AggregatedBy string `json:"aggregated_by,omitempty"`

	// The date and time, in UTC, the report was created. ISO 8601 Formatted.
	// Example: 2024-03-19T00:00:00Z
	CreatedAt string `json:"created_at,omitempty"`

	// How costs are grouped and displayed in the KubernetesEfficiencyReport. Possible values: day, week, month.
	// Example: month
	DateBucket string `json:"date_bucket,omitempty"`

	// The date range for the KubernetesEfficiencyReport. Only present if a custom date range is not specified.
	// Example: last_month
	DateInterval string `json:"date_interval,omitempty"`

	// Indicates whether the KubernetesEfficiencyReport is the default report.
	Default bool `json:"default,omitempty"`

	// The end date for the KubernetesEfficiencyReport. Only set for custom date ranges. ISO 8601 Formatted.
	// Example: 2024-03-20
	EndDate string `json:"end_date,omitempty"`

	// The filter applied to the KubernetesEfficiencyReport. Additional documentation available at https://docs.vantage.sh/vql.
	Filter string `json:"filter,omitempty"`

	// Grouping values for aggregating costs on the KubernetesEfficiencyReport. Valid groupings: cluster_id, namespace, labeled, category, label, label:<label_name>.
	// Example: cluster_id, namespace
	Groupings string `json:"groupings,omitempty"`

	// The start date for the KubernetesEfficiencyReport. Only set for custom date ranges. ISO 8601 Formatted.
	// Example: 2024-03-01
	StartDate string `json:"start_date,omitempty"`

	// The title of the KubernetesEfficiencyReport.
	// Example: Acme123 Kubernetes Efficiency Metrics
	Title string `json:"title,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// The token for the User who created this KubernetesEfficiencyReport.
	UserToken string `json:"user_token,omitempty"`

	// The token for the Workspace the KubernetesEfficiencyReport is a part of.
	WorkspaceToken string `json:"workspace_token,omitempty"`
}

// Validate validates this kubernetes efficiency report
func (m *KubernetesEfficiencyReport) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kubernetes efficiency report based on context it is used
func (m *KubernetesEfficiencyReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubernetesEfficiencyReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubernetesEfficiencyReport) UnmarshalBinary(b []byte) error {
	var res KubernetesEfficiencyReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
