// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCostReports Create a CostReport.
//
// swagger:model postCostReports
type PostCostReports struct {

	// The tokens of the BusinessMetrics to attach to the CostReport.
	BusinessMetricTokens []string `json:"business_metric_tokens"`

	// The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.
	Filter string `json:"filter,omitempty"`

	// The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.
	FolderToken string `json:"folder_token,omitempty"`

	// Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region
	Groupings string `json:"groupings,omitempty"`

	// The tokens of the SavedFilters to apply to the CostReport.
	SavedFilterTokens []string `json:"saved_filter_tokens"`

	// settings
	Settings *PostCostReportsSettings `json:"settings,omitempty"`

	// The title of the CostReport.
	// Required: true
	Title *string `json:"title"`

	// The token of the Workspace to add the Cost Report to. Ignored if 'folder_token' is set. Required if the API token is associated with multiple Workspaces.
	WorkspaceToken string `json:"workspace_token,omitempty"`
}

// Validate validates this post cost reports
func (m *PostCostReports) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCostReports) validateSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.Settings) { // not required
		return nil
	}

	if m.Settings != nil {
		if err := m.Settings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("settings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("settings")
			}
			return err
		}
	}

	return nil
}

func (m *PostCostReports) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this post cost reports based on the context it is used
func (m *PostCostReports) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCostReports) contextValidateSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.Settings != nil {

		if swag.IsZero(m.Settings) { // not required
			return nil
		}

		if err := m.Settings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("settings")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("settings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostCostReports) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCostReports) UnmarshalBinary(b []byte) error {
	var res PostCostReports
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PostCostReportsSettings Report settings.
//
// swagger:model PostCostReportsSettings
type PostCostReportsSettings struct {

	// Report will amortize.
	Amortize *bool `json:"amortize,omitempty"`

	// Report will include credits.
	IncludeCredits *bool `json:"include_credits,omitempty"`

	// Report will include discounts.
	IncludeDiscounts *bool `json:"include_discounts,omitempty"`

	// Report will include refunds.
	IncludeRefunds *bool `json:"include_refunds,omitempty"`

	// Report will include tax.
	IncludeTax *bool `json:"include_tax,omitempty"`

	// Report will show unallocated costs.
	Unallocated *bool `json:"unallocated,omitempty"`
}

// Validate validates this post cost reports settings
func (m *PostCostReportsSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post cost reports settings based on context it is used
func (m *PostCostReportsSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCostReportsSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCostReportsSettings) UnmarshalBinary(b []byte) error {
	var res PostCostReportsSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
