// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostTeams Create a new Team.
//
// swagger:model postTeams
type PostTeams struct {

	// The description of the Team.
	Description string `json:"description,omitempty"`

	// The name of the Team.
	// Required: true
	Name *string `json:"name"`

	// The role to assign to the provided Users. Defaults to 'editor' which has editor permissions.
	// Enum: [owner editor viewer]
	Role string `json:"role,omitempty"`

	// The User tokens to associate to the Team.
	UserTokens []string `json:"user_tokens"`

	// The Workspace tokens to associate to the Team.
	WorkspaceTokens []string `json:"workspace_tokens"`
}

// Validate validates this post teams
func (m *PostTeams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostTeams) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var postTeamsTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["owner","editor","viewer"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postTeamsTypeRolePropEnum = append(postTeamsTypeRolePropEnum, v)
	}
}

const (

	// PostTeamsRoleOwner captures enum value "owner"
	PostTeamsRoleOwner string = "owner"

	// PostTeamsRoleEditor captures enum value "editor"
	PostTeamsRoleEditor string = "editor"

	// PostTeamsRoleViewer captures enum value "viewer"
	PostTeamsRoleViewer string = "viewer"
)

// prop value enum
func (m *PostTeams) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postTeamsTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostTeams) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(m.Role) { // not required
		return nil
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post teams based on context it is used
func (m *PostTeams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostTeams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostTeams) UnmarshalBinary(b []byte) error {
	var res PostTeams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
