// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RecommendationAction recommendation action
//
// swagger:model RecommendationAction
type RecommendationAction struct {

	// action
	// Required: true
	Action string `json:"action"`

	// containers
	Containers string `json:"containers,omitempty"`

	// description
	// Required: true
	Description string `json:"description"`

	// instance type
	InstanceType string `json:"instance_type,omitempty"`

	// Potential savings in dollars
	// Example: 100.00
	// Required: true
	PotentialSavings string `json:"potential_savings"`

	// CLI command to remediate this recommendation
	// Example: aws ec2 stop-instances --instance-ids i-1234567890abcdef0
	RemediationCliCommand string `json:"remediation_cli_command,omitempty"`
}

// Validate validates this recommendation action
func (m *RecommendationAction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePotentialSavings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RecommendationAction) validateAction(formats strfmt.Registry) error {

	if err := validate.RequiredString("action", "body", m.Action); err != nil {
		return err
	}

	return nil
}

func (m *RecommendationAction) validateDescription(formats strfmt.Registry) error {

	if err := validate.RequiredString("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *RecommendationAction) validatePotentialSavings(formats strfmt.Registry) error {

	if err := validate.RequiredString("potential_savings", "body", m.PotentialSavings); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this recommendation action based on context it is used
func (m *RecommendationAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecommendationAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecommendationAction) UnmarshalBinary(b []byte) error {
	var res RecommendationAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
