// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScenarioModelPeriod scenario model period
//
// swagger:model ScenarioModelPeriod
type ScenarioModelPeriod struct {

	// The period amount as a string to preserve decimal precision.
	// Example: 1250.75
	// Required: true
	Amount string `json:"amount"`

	// Whether the amount is in dollars or percent.
	// Required: true
	// Enum: ["dollar","percent"]
	AmountType string `json:"amount_type"`

	// The ISO 8601 end date of the period.
	// Example: 2026-03-31
	// Required: true
	EndAt *string `json:"end_at"`

	// The ISO 8601 start date of the period.
	// Example: 2026-01-01
	// Required: true
	StartAt string `json:"start_at"`
}

// Validate validates this scenario model period
func (m *ScenarioModelPeriod) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmountType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScenarioModelPeriod) validateAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

var scenarioModelPeriodTypeAmountTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dollar","percent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		scenarioModelPeriodTypeAmountTypePropEnum = append(scenarioModelPeriodTypeAmountTypePropEnum, v)
	}
}

const (

	// ScenarioModelPeriodAmountTypeDollar captures enum value "dollar"
	ScenarioModelPeriodAmountTypeDollar string = "dollar"

	// ScenarioModelPeriodAmountTypePercent captures enum value "percent"
	ScenarioModelPeriodAmountTypePercent string = "percent"
)

// prop value enum
func (m *ScenarioModelPeriod) validateAmountTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, scenarioModelPeriodTypeAmountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ScenarioModelPeriod) validateAmountType(formats strfmt.Registry) error {

	if err := validate.RequiredString("amount_type", "body", m.AmountType); err != nil {
		return err
	}

	// value enum
	if err := m.validateAmountTypeEnum("amount_type", "body", m.AmountType); err != nil {
		return err
	}

	return nil
}

func (m *ScenarioModelPeriod) validateEndAt(formats strfmt.Registry) error {

	if err := validate.Required("end_at", "body", m.EndAt); err != nil {
		return err
	}

	return nil
}

func (m *ScenarioModelPeriod) validateStartAt(formats strfmt.Registry) error {

	if err := validate.RequiredString("start_at", "body", m.StartAt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this scenario model period based on context it is used
func (m *ScenarioModelPeriod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScenarioModelPeriod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScenarioModelPeriod) UnmarshalBinary(b []byte) error {
	var res ScenarioModelPeriod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
