// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnitCost unit cost
//
// swagger:model UnitCost
type UnitCost struct {

	// The amount of the business metric.
	// Example: 0.371
	// Required: true
	BusinessMetricAmount string `json:"business_metric_amount"`

	// The title of the BusinessMetric for which the unit cost was calculated.
	// Example: Total Revenue
	// Required: true
	BusinessMetricTitle string `json:"business_metric_title"`

	// The token of the BusinessMetric for which the unit cost was calculated.
	// Example: bsnss_mtrc_1234
	// Required: true
	BusinessMetricToken string `json:"business_metric_token"`

	// The calculation type applied to produce this result.
	// Example: unit_cost
	// Enum: ["unit_cost","gross_margin","usage_unit_cost","raw_business_metric"]
	CalculationType *string `json:"calculation_type,omitempty"`

	// The date for which the unit cost was calculated. ISO 8601 Formatted.
	// Example: 2023-09-05+00:00
	// Required: true
	Date string `json:"date"`

	// links
	Links *Links `json:"links,omitempty"`

	// The scale of the BusinessMetric's values within a particular CostReport.
	// Example: 1
	// Required: true
	Scale float32 `json:"scale"`

	// The amount of the unit cost. For raw_business_metric types, this equals the business_metric_amount.
	// Example: 4.25
	// Required: true
	UnitCostAmount string `json:"unit_cost_amount"`
}

// Validate validates this unit cost
func (m *UnitCost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBusinessMetricAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBusinessMetricTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBusinessMetricToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCalculationType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnitCostAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnitCost) validateBusinessMetricAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("business_metric_amount", "body", m.BusinessMetricAmount); err != nil {
		return err
	}

	return nil
}

func (m *UnitCost) validateBusinessMetricTitle(formats strfmt.Registry) error {

	if err := validate.RequiredString("business_metric_title", "body", m.BusinessMetricTitle); err != nil {
		return err
	}

	return nil
}

func (m *UnitCost) validateBusinessMetricToken(formats strfmt.Registry) error {

	if err := validate.RequiredString("business_metric_token", "body", m.BusinessMetricToken); err != nil {
		return err
	}

	return nil
}

var unitCostTypeCalculationTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["unit_cost","gross_margin","usage_unit_cost","raw_business_metric"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		unitCostTypeCalculationTypePropEnum = append(unitCostTypeCalculationTypePropEnum, v)
	}
}

const (

	// UnitCostCalculationTypeUnitCost captures enum value "unit_cost"
	UnitCostCalculationTypeUnitCost string = "unit_cost"

	// UnitCostCalculationTypeGrossMargin captures enum value "gross_margin"
	UnitCostCalculationTypeGrossMargin string = "gross_margin"

	// UnitCostCalculationTypeUsageUnitCost captures enum value "usage_unit_cost"
	UnitCostCalculationTypeUsageUnitCost string = "usage_unit_cost"

	// UnitCostCalculationTypeRawBusinessMetric captures enum value "raw_business_metric"
	UnitCostCalculationTypeRawBusinessMetric string = "raw_business_metric"
)

// prop value enum
func (m *UnitCost) validateCalculationTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, unitCostTypeCalculationTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UnitCost) validateCalculationType(formats strfmt.Registry) error {
	if swag.IsZero(m.CalculationType) { // not required
		return nil
	}

	// value enum
	if err := m.validateCalculationTypeEnum("calculation_type", "body", *m.CalculationType); err != nil {
		return err
	}

	return nil
}

func (m *UnitCost) validateDate(formats strfmt.Registry) error {

	if err := validate.RequiredString("date", "body", m.Date); err != nil {
		return err
	}

	return nil
}

func (m *UnitCost) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

func (m *UnitCost) validateScale(formats strfmt.Registry) error {

	if err := validate.Required("scale", "body", float32(m.Scale)); err != nil {
		return err
	}

	return nil
}

func (m *UnitCost) validateUnitCostAmount(formats strfmt.Registry) error {

	if err := validate.RequiredString("unit_cost_amount", "body", m.UnitCostAmount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this unit cost based on the context it is used
func (m *UnitCost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnitCost) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if m.Links != nil {

		if swag.IsZero(m.Links) { // not required
			return nil
		}

		if err := m.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnitCost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnitCost) UnmarshalBinary(b []byte) error {
	var res UnitCost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
