// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateBusinessMetric Updates an existing BusinessMetric.
//
// swagger:model updateBusinessMetric
type UpdateBusinessMetric struct {

	// The tokens for any CostReports that use the BusinessMetric, and the unit scale.
	CostReportTokensWithMetadata []*UpdateBusinessMetricCostReportTokensWithMetadataItems0 `json:"cost_report_tokens_with_metadata"`

	// The title of the BusinessMetric.
	Title string `json:"title,omitempty"`

	// The dates and amounts for the BusinessMetric.
	Values []*UpdateBusinessMetricValuesItems0 `json:"values"`
}

// Validate validates this update business metric
func (m *UpdateBusinessMetric) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCostReportTokensWithMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateBusinessMetric) validateCostReportTokensWithMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.CostReportTokensWithMetadata) { // not required
		return nil
	}

	for i := 0; i < len(m.CostReportTokensWithMetadata); i++ {
		if swag.IsZero(m.CostReportTokensWithMetadata[i]) { // not required
			continue
		}

		if m.CostReportTokensWithMetadata[i] != nil {
			if err := m.CostReportTokensWithMetadata[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cost_report_tokens_with_metadata" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cost_report_tokens_with_metadata" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateBusinessMetric) validateValues(formats strfmt.Registry) error {
	if swag.IsZero(m.Values) { // not required
		return nil
	}

	for i := 0; i < len(m.Values); i++ {
		if swag.IsZero(m.Values[i]) { // not required
			continue
		}

		if m.Values[i] != nil {
			if err := m.Values[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this update business metric based on the context it is used
func (m *UpdateBusinessMetric) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCostReportTokensWithMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateBusinessMetric) contextValidateCostReportTokensWithMetadata(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CostReportTokensWithMetadata); i++ {

		if m.CostReportTokensWithMetadata[i] != nil {

			if swag.IsZero(m.CostReportTokensWithMetadata[i]) { // not required
				return nil
			}

			if err := m.CostReportTokensWithMetadata[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cost_report_tokens_with_metadata" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cost_report_tokens_with_metadata" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateBusinessMetric) contextValidateValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Values); i++ {

		if m.Values[i] != nil {

			if swag.IsZero(m.Values[i]) { // not required
				return nil
			}

			if err := m.Values[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateBusinessMetric) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateBusinessMetric) UnmarshalBinary(b []byte) error {
	var res UpdateBusinessMetric
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UpdateBusinessMetricCostReportTokensWithMetadataItems0 update business metric cost report tokens with metadata items0
//
// swagger:model UpdateBusinessMetricCostReportTokensWithMetadataItems0
type UpdateBusinessMetricCostReportTokensWithMetadataItems0 struct {

	// The token of the CostReport the BusinessMetric is attached to.
	// Required: true
	CostReportToken *string `json:"cost_report_token"`

	// Determines the scale of the BusinessMetric's values within the CostReport.
	// Enum: [per_unit per_hundred per_thousand per_million per_billion]
	UnitScale *string `json:"unit_scale,omitempty"`
}

// Validate validates this update business metric cost report tokens with metadata items0
func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCostReportToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnitScale(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) validateCostReportToken(formats strfmt.Registry) error {

	if err := validate.Required("cost_report_token", "body", m.CostReportToken); err != nil {
		return err
	}

	return nil
}

var updateBusinessMetricCostReportTokensWithMetadataItems0TypeUnitScalePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["per_unit","per_hundred","per_thousand","per_million","per_billion"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateBusinessMetricCostReportTokensWithMetadataItems0TypeUnitScalePropEnum = append(updateBusinessMetricCostReportTokensWithMetadataItems0TypeUnitScalePropEnum, v)
	}
}

const (

	// UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerUnit captures enum value "per_unit"
	UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerUnit string = "per_unit"

	// UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerHundred captures enum value "per_hundred"
	UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerHundred string = "per_hundred"

	// UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerThousand captures enum value "per_thousand"
	UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerThousand string = "per_thousand"

	// UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerMillion captures enum value "per_million"
	UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerMillion string = "per_million"

	// UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerBillion captures enum value "per_billion"
	UpdateBusinessMetricCostReportTokensWithMetadataItems0UnitScalePerBillion string = "per_billion"
)

// prop value enum
func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) validateUnitScaleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateBusinessMetricCostReportTokensWithMetadataItems0TypeUnitScalePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) validateUnitScale(formats strfmt.Registry) error {
	if swag.IsZero(m.UnitScale) { // not required
		return nil
	}

	// value enum
	if err := m.validateUnitScaleEnum("unit_scale", "body", *m.UnitScale); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update business metric cost report tokens with metadata items0 based on context it is used
func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateBusinessMetricCostReportTokensWithMetadataItems0) UnmarshalBinary(b []byte) error {
	var res UpdateBusinessMetricCostReportTokensWithMetadataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// UpdateBusinessMetricValuesItems0 update business metric values items0
//
// swagger:model UpdateBusinessMetricValuesItems0
type UpdateBusinessMetricValuesItems0 struct {

	// amount
	// Required: true
	Amount *float64 `json:"amount"`

	// date
	// Required: true
	// Format: date-time
	Date *strfmt.DateTime `json:"date"`
}

// Validate validates this update business metric values items0
func (m *UpdateBusinessMetricValuesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateBusinessMetricValuesItems0) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *UpdateBusinessMetricValuesItems0) validateDate(formats strfmt.Registry) error {

	if err := validate.Required("date", "body", m.Date); err != nil {
		return err
	}

	if err := validate.FormatOf("date", "body", "date-time", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update business metric values items0 based on context it is used
func (m *UpdateBusinessMetricValuesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateBusinessMetricValuesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateBusinessMetricValuesItems0) UnmarshalBinary(b []byte) error {
	var res UpdateBusinessMetricValuesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
