// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRecommendationView Update a RecommendationView.
//
// swagger:model updateRecommendationView
type UpdateRecommendationView struct {

	// Filter by cloud account identifiers.
	AccountIds []string `json:"account_ids"`

	// Filter by billing account identifiers.
	BillingAccountIds []string `json:"billing_account_ids"`

	// Filter recommendations created on/before this YYYY-MM-DD date.
	EndDate string `json:"end_date,omitempty"`

	// Filter by one or more providers (e.g. aws, gcp, azure, kubernetes, datadog).
	ProviderIds []string `json:"provider_ids"`

	// Filter by region slugs (e.g. us-east-1, eastus, asia-east1).
	Regions []string `json:"regions"`

	// Filter recommendations created on/after this YYYY-MM-DD date.
	StartDate string `json:"start_date,omitempty"`

	// Filter by tag key (must be used with tag_value).
	TagKey string `json:"tag_key,omitempty"`

	// Filter by tag value (requires tag_key).
	TagValue string `json:"tag_value,omitempty"`

	// The title of the RecommendationView.
	Title string `json:"title,omitempty"`
}

// Validate validates this update recommendation view
func (m *UpdateRecommendationView) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update recommendation view based on context it is used
func (m *UpdateRecommendationView) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRecommendationView) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRecommendationView) UnmarshalBinary(b []byte) error {
	var res UpdateRecommendationView
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
