// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserCostsUploads UserCostsUploads model
//
// swagger:model UserCostsUploads
type UserCostsUploads struct {

	// user costs uploads
	UserCostsUploads []*UserCostsUpload `json:"user_costs_uploads"`
}

// Validate validates this user costs uploads
func (m *UserCostsUploads) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserCostsUploads(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserCostsUploads) validateUserCostsUploads(formats strfmt.Registry) error {
	if swag.IsZero(m.UserCostsUploads) { // not required
		return nil
	}

	for i := 0; i < len(m.UserCostsUploads); i++ {
		if swag.IsZero(m.UserCostsUploads[i]) { // not required
			continue
		}

		if m.UserCostsUploads[i] != nil {
			if err := m.UserCostsUploads[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("user_costs_uploads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("user_costs_uploads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this user costs uploads based on the context it is used
func (m *UserCostsUploads) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUserCostsUploads(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserCostsUploads) contextValidateUserCostsUploads(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.UserCostsUploads); i++ {

		if m.UserCostsUploads[i] != nil {

			if swag.IsZero(m.UserCostsUploads[i]) { // not required
				return nil
			}

			if err := m.UserCostsUploads[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("user_costs_uploads" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("user_costs_uploads" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserCostsUploads) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCostsUploads) UnmarshalBinary(b []byte) error {
	var res UserCostsUploads
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
