// Code generated by go-swagger; DO NOT EDIT.

package billing_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetBillingProfileReader is a Reader for the GetBillingProfile structure.
type GetBillingProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBillingProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBillingProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetBillingProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /billing_profiles/{billing_profile_token}] getBillingProfile", response, response.Code())
	}
}

// NewGetBillingProfileOK creates a GetBillingProfileOK with default headers values
func NewGetBillingProfileOK() *GetBillingProfileOK {
	return &GetBillingProfileOK{}
}

/*
GetBillingProfileOK describes a response with status code 200, with default header values.

GetBillingProfileOK get billing profile o k
*/
type GetBillingProfileOK struct {
	Payload *models.BillingProfile
}

// IsSuccess returns true when this get billing profile o k response has a 2xx status code
func (o *GetBillingProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get billing profile o k response has a 3xx status code
func (o *GetBillingProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get billing profile o k response has a 4xx status code
func (o *GetBillingProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get billing profile o k response has a 5xx status code
func (o *GetBillingProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get billing profile o k response a status code equal to that given
func (o *GetBillingProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get billing profile o k response
func (o *GetBillingProfileOK) Code() int {
	return 200
}

func (o *GetBillingProfileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /billing_profiles/{billing_profile_token}][%d] getBillingProfileOK %s", 200, payload)
}

func (o *GetBillingProfileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /billing_profiles/{billing_profile_token}][%d] getBillingProfileOK %s", 200, payload)
}

func (o *GetBillingProfileOK) GetPayload() *models.BillingProfile {
	return o.Payload
}

func (o *GetBillingProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBillingProfileNotFound creates a GetBillingProfileNotFound with default headers values
func NewGetBillingProfileNotFound() *GetBillingProfileNotFound {
	return &GetBillingProfileNotFound{}
}

/*
GetBillingProfileNotFound describes a response with status code 404, with default header values.

NotFound
*/
type GetBillingProfileNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get billing profile not found response has a 2xx status code
func (o *GetBillingProfileNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get billing profile not found response has a 3xx status code
func (o *GetBillingProfileNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get billing profile not found response has a 4xx status code
func (o *GetBillingProfileNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get billing profile not found response has a 5xx status code
func (o *GetBillingProfileNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get billing profile not found response a status code equal to that given
func (o *GetBillingProfileNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get billing profile not found response
func (o *GetBillingProfileNotFound) Code() int {
	return 404
}

func (o *GetBillingProfileNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /billing_profiles/{billing_profile_token}][%d] getBillingProfileNotFound %s", 404, payload)
}

func (o *GetBillingProfileNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /billing_profiles/{billing_profile_token}][%d] getBillingProfileNotFound %s", 404, payload)
}

func (o *GetBillingProfileNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetBillingProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
