// Code generated by go-swagger; DO NOT EDIT.

package report_alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// NewUpdateReportAlertParams creates a new UpdateReportAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateReportAlertParams() *UpdateReportAlertParams {
	return &UpdateReportAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateReportAlertParamsWithTimeout creates a new UpdateReportAlertParams object
// with the ability to set a timeout on a request.
func NewUpdateReportAlertParamsWithTimeout(timeout time.Duration) *UpdateReportAlertParams {
	return &UpdateReportAlertParams{
		timeout: timeout,
	}
}

// NewUpdateReportAlertParamsWithContext creates a new UpdateReportAlertParams object
// with the ability to set a context for a request.
func NewUpdateReportAlertParamsWithContext(ctx context.Context) *UpdateReportAlertParams {
	return &UpdateReportAlertParams{
		Context: ctx,
	}
}

// NewUpdateReportAlertParamsWithHTTPClient creates a new UpdateReportAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateReportAlertParamsWithHTTPClient(client *http.Client) *UpdateReportAlertParams {
	return &UpdateReportAlertParams{
		HTTPClient: client,
	}
}

/*
UpdateReportAlertParams contains all the parameters to send to the API endpoint

	for the update report alert operation.

	Typically these are written to a http.Request.
*/
type UpdateReportAlertParams struct {

	// ReportAlerts.
	ReportAlerts *models.PutReportAlerts

	// ReportAlertToken.
	ReportAlertToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update report alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateReportAlertParams) WithDefaults() *UpdateReportAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update report alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateReportAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update report alert params
func (o *UpdateReportAlertParams) WithTimeout(timeout time.Duration) *UpdateReportAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update report alert params
func (o *UpdateReportAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update report alert params
func (o *UpdateReportAlertParams) WithContext(ctx context.Context) *UpdateReportAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update report alert params
func (o *UpdateReportAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update report alert params
func (o *UpdateReportAlertParams) WithHTTPClient(client *http.Client) *UpdateReportAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update report alert params
func (o *UpdateReportAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReportAlerts adds the reportAlerts to the update report alert params
func (o *UpdateReportAlertParams) WithReportAlerts(reportAlerts *models.PutReportAlerts) *UpdateReportAlertParams {
	o.SetReportAlerts(reportAlerts)
	return o
}

// SetReportAlerts adds the reportAlerts to the update report alert params
func (o *UpdateReportAlertParams) SetReportAlerts(reportAlerts *models.PutReportAlerts) {
	o.ReportAlerts = reportAlerts
}

// WithReportAlertToken adds the reportAlertToken to the update report alert params
func (o *UpdateReportAlertParams) WithReportAlertToken(reportAlertToken string) *UpdateReportAlertParams {
	o.SetReportAlertToken(reportAlertToken)
	return o
}

// SetReportAlertToken adds the reportAlertToken to the update report alert params
func (o *UpdateReportAlertParams) SetReportAlertToken(reportAlertToken string) {
	o.ReportAlertToken = reportAlertToken
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateReportAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ReportAlerts != nil {
		if err := r.SetBodyParam(o.ReportAlerts); err != nil {
			return err
		}
	}

	// path param report_alert_token
	if err := r.SetPathParam("report_alert_token", o.ReportAlertToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
