// Code generated by go-swagger; DO NOT EDIT.

package costs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// NewCreateCostReportFolderParams creates a new CreateCostReportFolderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCostReportFolderParams() *CreateCostReportFolderParams {
	return &CreateCostReportFolderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCostReportFolderParamsWithTimeout creates a new CreateCostReportFolderParams object
// with the ability to set a timeout on a request.
func NewCreateCostReportFolderParamsWithTimeout(timeout time.Duration) *CreateCostReportFolderParams {
	return &CreateCostReportFolderParams{
		timeout: timeout,
	}
}

// NewCreateCostReportFolderParamsWithContext creates a new CreateCostReportFolderParams object
// with the ability to set a context for a request.
func NewCreateCostReportFolderParamsWithContext(ctx context.Context) *CreateCostReportFolderParams {
	return &CreateCostReportFolderParams{
		Context: ctx,
	}
}

// NewCreateCostReportFolderParamsWithHTTPClient creates a new CreateCostReportFolderParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCostReportFolderParamsWithHTTPClient(client *http.Client) *CreateCostReportFolderParams {
	return &CreateCostReportFolderParams{
		HTTPClient: client,
	}
}

/*
CreateCostReportFolderParams contains all the parameters to send to the API endpoint

	for the create cost report folder operation.

	Typically these are written to a http.Request.
*/
type CreateCostReportFolderParams struct {

	// Folders.
	Folders *models.PostFolders

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create cost report folder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCostReportFolderParams) WithDefaults() *CreateCostReportFolderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create cost report folder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCostReportFolderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create cost report folder params
func (o *CreateCostReportFolderParams) WithTimeout(timeout time.Duration) *CreateCostReportFolderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cost report folder params
func (o *CreateCostReportFolderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cost report folder params
func (o *CreateCostReportFolderParams) WithContext(ctx context.Context) *CreateCostReportFolderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cost report folder params
func (o *CreateCostReportFolderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cost report folder params
func (o *CreateCostReportFolderParams) WithHTTPClient(client *http.Client) *CreateCostReportFolderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cost report folder params
func (o *CreateCostReportFolderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFolders adds the folders to the create cost report folder params
func (o *CreateCostReportFolderParams) WithFolders(folders *models.PostFolders) *CreateCostReportFolderParams {
	o.SetFolders(folders)
	return o
}

// SetFolders adds the folders to the create cost report folder params
func (o *CreateCostReportFolderParams) SetFolders(folders *models.PostFolders) {
	o.Folders = folders
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCostReportFolderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Folders != nil {
		if err := r.SetBodyParam(o.Folders); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
