// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// RemoveTeamMemberReader is a Reader for the RemoveTeamMember structure.
type RemoveTeamMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveTeamMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveTeamMemberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveTeamMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRemoveTeamMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRemoveTeamMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /teams/{team_token}/members/{user_token}] removeTeamMember", response, response.Code())
	}
}

// NewRemoveTeamMemberNoContent creates a RemoveTeamMemberNoContent with default headers values
func NewRemoveTeamMemberNoContent() *RemoveTeamMemberNoContent {
	return &RemoveTeamMemberNoContent{}
}

/*
RemoveTeamMemberNoContent describes a response with status code 204, with default header values.

RemoveTeamMemberNoContent remove team member no content
*/
type RemoveTeamMemberNoContent struct {
}

// IsSuccess returns true when this remove team member no content response has a 2xx status code
func (o *RemoveTeamMemberNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove team member no content response has a 3xx status code
func (o *RemoveTeamMemberNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove team member no content response has a 4xx status code
func (o *RemoveTeamMemberNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove team member no content response has a 5xx status code
func (o *RemoveTeamMemberNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this remove team member no content response a status code equal to that given
func (o *RemoveTeamMemberNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the remove team member no content response
func (o *RemoveTeamMemberNoContent) Code() int {
	return 204
}

func (o *RemoveTeamMemberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberNoContent", 204)
}

func (o *RemoveTeamMemberNoContent) String() string {
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberNoContent", 204)
}

func (o *RemoveTeamMemberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemoveTeamMemberBadRequest creates a RemoveTeamMemberBadRequest with default headers values
func NewRemoveTeamMemberBadRequest() *RemoveTeamMemberBadRequest {
	return &RemoveTeamMemberBadRequest{}
}

/*
RemoveTeamMemberBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type RemoveTeamMemberBadRequest struct {
	Payload *models.Errors
}

// IsSuccess returns true when this remove team member bad request response has a 2xx status code
func (o *RemoveTeamMemberBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove team member bad request response has a 3xx status code
func (o *RemoveTeamMemberBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove team member bad request response has a 4xx status code
func (o *RemoveTeamMemberBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove team member bad request response has a 5xx status code
func (o *RemoveTeamMemberBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this remove team member bad request response a status code equal to that given
func (o *RemoveTeamMemberBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the remove team member bad request response
func (o *RemoveTeamMemberBadRequest) Code() int {
	return 400
}

func (o *RemoveTeamMemberBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberBadRequest %s", 400, payload)
}

func (o *RemoveTeamMemberBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberBadRequest %s", 400, payload)
}

func (o *RemoveTeamMemberBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *RemoveTeamMemberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTeamMemberForbidden creates a RemoveTeamMemberForbidden with default headers values
func NewRemoveTeamMemberForbidden() *RemoveTeamMemberForbidden {
	return &RemoveTeamMemberForbidden{}
}

/*
RemoveTeamMemberForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type RemoveTeamMemberForbidden struct {
	Payload *models.Errors
}

// IsSuccess returns true when this remove team member forbidden response has a 2xx status code
func (o *RemoveTeamMemberForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove team member forbidden response has a 3xx status code
func (o *RemoveTeamMemberForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove team member forbidden response has a 4xx status code
func (o *RemoveTeamMemberForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove team member forbidden response has a 5xx status code
func (o *RemoveTeamMemberForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this remove team member forbidden response a status code equal to that given
func (o *RemoveTeamMemberForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the remove team member forbidden response
func (o *RemoveTeamMemberForbidden) Code() int {
	return 403
}

func (o *RemoveTeamMemberForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberForbidden %s", 403, payload)
}

func (o *RemoveTeamMemberForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberForbidden %s", 403, payload)
}

func (o *RemoveTeamMemberForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *RemoveTeamMemberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveTeamMemberNotFound creates a RemoveTeamMemberNotFound with default headers values
func NewRemoveTeamMemberNotFound() *RemoveTeamMemberNotFound {
	return &RemoveTeamMemberNotFound{}
}

/*
RemoveTeamMemberNotFound describes a response with status code 404, with default header values.

NotFound
*/
type RemoveTeamMemberNotFound struct {
	Payload *models.Errors
}

// IsSuccess returns true when this remove team member not found response has a 2xx status code
func (o *RemoveTeamMemberNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this remove team member not found response has a 3xx status code
func (o *RemoveTeamMemberNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove team member not found response has a 4xx status code
func (o *RemoveTeamMemberNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this remove team member not found response has a 5xx status code
func (o *RemoveTeamMemberNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this remove team member not found response a status code equal to that given
func (o *RemoveTeamMemberNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the remove team member not found response
func (o *RemoveTeamMemberNotFound) Code() int {
	return 404
}

func (o *RemoveTeamMemberNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberNotFound %s", 404, payload)
}

func (o *RemoveTeamMemberNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /teams/{team_token}/members/{user_token}][%d] removeTeamMemberNotFound %s", 404, payload)
}

func (o *RemoveTeamMemberNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *RemoveTeamMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
