// Code generated by go-swagger; DO NOT EDIT.

package resource_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetResourceReportColumnsReader is a Reader for the GetResourceReportColumns structure.
type GetResourceReportColumnsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResourceReportColumnsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResourceReportColumnsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetResourceReportColumnsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /resource_reports/columns] getResourceReportColumns", response, response.Code())
	}
}

// NewGetResourceReportColumnsOK creates a GetResourceReportColumnsOK with default headers values
func NewGetResourceReportColumnsOK() *GetResourceReportColumnsOK {
	return &GetResourceReportColumnsOK{}
}

/*
GetResourceReportColumnsOK describes a response with status code 200, with default header values.

Returns array of available column names for the specified resource type
*/
type GetResourceReportColumnsOK struct {
	Payload *models.ResourceReportColumns
}

// IsSuccess returns true when this get resource report columns o k response has a 2xx status code
func (o *GetResourceReportColumnsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get resource report columns o k response has a 3xx status code
func (o *GetResourceReportColumnsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resource report columns o k response has a 4xx status code
func (o *GetResourceReportColumnsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get resource report columns o k response has a 5xx status code
func (o *GetResourceReportColumnsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get resource report columns o k response a status code equal to that given
func (o *GetResourceReportColumnsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get resource report columns o k response
func (o *GetResourceReportColumnsOK) Code() int {
	return 200
}

func (o *GetResourceReportColumnsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /resource_reports/columns][%d] getResourceReportColumnsOK %s", 200, payload)
}

func (o *GetResourceReportColumnsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /resource_reports/columns][%d] getResourceReportColumnsOK %s", 200, payload)
}

func (o *GetResourceReportColumnsOK) GetPayload() *models.ResourceReportColumns {
	return o.Payload
}

func (o *GetResourceReportColumnsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceReportColumns)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetResourceReportColumnsBadRequest creates a GetResourceReportColumnsBadRequest with default headers values
func NewGetResourceReportColumnsBadRequest() *GetResourceReportColumnsBadRequest {
	return &GetResourceReportColumnsBadRequest{}
}

/*
GetResourceReportColumnsBadRequest describes a response with status code 400, with default header values.

BadRequest
*/
type GetResourceReportColumnsBadRequest struct {
	Payload *models.Errors
}

// IsSuccess returns true when this get resource report columns bad request response has a 2xx status code
func (o *GetResourceReportColumnsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get resource report columns bad request response has a 3xx status code
func (o *GetResourceReportColumnsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get resource report columns bad request response has a 4xx status code
func (o *GetResourceReportColumnsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get resource report columns bad request response has a 5xx status code
func (o *GetResourceReportColumnsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get resource report columns bad request response a status code equal to that given
func (o *GetResourceReportColumnsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get resource report columns bad request response
func (o *GetResourceReportColumnsBadRequest) Code() int {
	return 400
}

func (o *GetResourceReportColumnsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /resource_reports/columns][%d] getResourceReportColumnsBadRequest %s", 400, payload)
}

func (o *GetResourceReportColumnsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /resource_reports/columns][%d] getResourceReportColumnsBadRequest %s", 400, payload)
}

func (o *GetResourceReportColumnsBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetResourceReportColumnsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
