// Code generated by go-swagger; DO NOT EDIT.

package kubernetes_efficiency_reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateKubernetesEfficiencyReportExportParams creates a new CreateKubernetesEfficiencyReportExportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateKubernetesEfficiencyReportExportParams() *CreateKubernetesEfficiencyReportExportParams {
	return &CreateKubernetesEfficiencyReportExportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateKubernetesEfficiencyReportExportParamsWithTimeout creates a new CreateKubernetesEfficiencyReportExportParams object
// with the ability to set a timeout on a request.
func NewCreateKubernetesEfficiencyReportExportParamsWithTimeout(timeout time.Duration) *CreateKubernetesEfficiencyReportExportParams {
	return &CreateKubernetesEfficiencyReportExportParams{
		timeout: timeout,
	}
}

// NewCreateKubernetesEfficiencyReportExportParamsWithContext creates a new CreateKubernetesEfficiencyReportExportParams object
// with the ability to set a context for a request.
func NewCreateKubernetesEfficiencyReportExportParamsWithContext(ctx context.Context) *CreateKubernetesEfficiencyReportExportParams {
	return &CreateKubernetesEfficiencyReportExportParams{
		Context: ctx,
	}
}

// NewCreateKubernetesEfficiencyReportExportParamsWithHTTPClient creates a new CreateKubernetesEfficiencyReportExportParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateKubernetesEfficiencyReportExportParamsWithHTTPClient(client *http.Client) *CreateKubernetesEfficiencyReportExportParams {
	return &CreateKubernetesEfficiencyReportExportParams{
		HTTPClient: client,
	}
}

/*
CreateKubernetesEfficiencyReportExportParams contains all the parameters to send to the API endpoint

	for the create kubernetes efficiency report export operation.

	Typically these are written to a http.Request.
*/
type CreateKubernetesEfficiencyReportExportParams struct {

	/* DateBin.

	   The date bin of the data. Defaults to the report's default or day.
	*/
	DateBin *string

	/* EndDate.

	   Last date you would like to filter data to. ISO 8601 formatted.
	*/
	EndDate *string

	/* Filter.

	   The filter query language to apply to the KubernetesEfficiencyReport. Additional documentation available at https://docs.vantage.sh/vql.
	*/
	Filter *string

	/* Groupings.

	   Group the results by specific field(s). Valid groupings: cluster_id, namespace, labeled, category, pod, label, label:<label_name>.
	*/
	Groupings []string

	/* KubernetesEfficiencyReportToken.

	   The KubernetesEfficiencyReport token. If not provided, the default report for the workspace will be used.
	*/
	KubernetesEfficiencyReportToken *string

	/* StartDate.

	   First date you would like to filter data from. ISO 8601 formatted.
	*/
	StartDate *string

	/* WorkspaceToken.

	   The token of the Workspace to export data from. Ignored if 'kubernetes_efficiency_report_token' is set. Required if the API token is associated with multiple Workspaces.
	*/
	WorkspaceToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create kubernetes efficiency report export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKubernetesEfficiencyReportExportParams) WithDefaults() *CreateKubernetesEfficiencyReportExportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create kubernetes efficiency report export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKubernetesEfficiencyReportExportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithTimeout(timeout time.Duration) *CreateKubernetesEfficiencyReportExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithContext(ctx context.Context) *CreateKubernetesEfficiencyReportExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithHTTPClient(client *http.Client) *CreateKubernetesEfficiencyReportExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDateBin adds the dateBin to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithDateBin(dateBin *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetDateBin(dateBin)
	return o
}

// SetDateBin adds the dateBin to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetDateBin(dateBin *string) {
	o.DateBin = dateBin
}

// WithEndDate adds the endDate to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithEndDate(endDate *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetEndDate(endDate *string) {
	o.EndDate = endDate
}

// WithFilter adds the filter to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithFilter(filter *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithGroupings adds the groupings to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithGroupings(groupings []string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetGroupings(groupings)
	return o
}

// SetGroupings adds the groupings to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetGroupings(groupings []string) {
	o.Groupings = groupings
}

// WithKubernetesEfficiencyReportToken adds the kubernetesEfficiencyReportToken to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithKubernetesEfficiencyReportToken(kubernetesEfficiencyReportToken *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetKubernetesEfficiencyReportToken(kubernetesEfficiencyReportToken)
	return o
}

// SetKubernetesEfficiencyReportToken adds the kubernetesEfficiencyReportToken to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetKubernetesEfficiencyReportToken(kubernetesEfficiencyReportToken *string) {
	o.KubernetesEfficiencyReportToken = kubernetesEfficiencyReportToken
}

// WithStartDate adds the startDate to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithStartDate(startDate *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetStartDate(startDate)
	return o
}

// SetStartDate adds the startDate to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetStartDate(startDate *string) {
	o.StartDate = startDate
}

// WithWorkspaceToken adds the workspaceToken to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) WithWorkspaceToken(workspaceToken *string) *CreateKubernetesEfficiencyReportExportParams {
	o.SetWorkspaceToken(workspaceToken)
	return o
}

// SetWorkspaceToken adds the workspaceToken to the create kubernetes efficiency report export params
func (o *CreateKubernetesEfficiencyReportExportParams) SetWorkspaceToken(workspaceToken *string) {
	o.WorkspaceToken = workspaceToken
}

// WriteToRequest writes these params to a swagger request
func (o *CreateKubernetesEfficiencyReportExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DateBin != nil {

		// form param date_bin
		var frDateBin string
		if o.DateBin != nil {
			frDateBin = *o.DateBin
		}
		fDateBin := frDateBin
		if fDateBin != "" {
			if err := r.SetFormParam("date_bin", fDateBin); err != nil {
				return err
			}
		}
	}

	if o.EndDate != nil {

		// form param end_date
		var frEndDate string
		if o.EndDate != nil {
			frEndDate = *o.EndDate
		}
		fEndDate := frEndDate
		if fEndDate != "" {
			if err := r.SetFormParam("end_date", fEndDate); err != nil {
				return err
			}
		}
	}

	if o.Filter != nil {

		// form param filter
		var frFilter string
		if o.Filter != nil {
			frFilter = *o.Filter
		}
		fFilter := frFilter
		if fFilter != "" {
			if err := r.SetFormParam("filter", fFilter); err != nil {
				return err
			}
		}
	}

	if o.Groupings != nil {

		// binding items for groupings
		joinedGroupings := o.bindParamGroupings(reg)

		// query array param groupings
		if err := r.SetQueryParam("groupings", joinedGroupings...); err != nil {
			return err
		}
	}

	if o.KubernetesEfficiencyReportToken != nil {

		// form param kubernetes_efficiency_report_token
		var frKubernetesEfficiencyReportToken string
		if o.KubernetesEfficiencyReportToken != nil {
			frKubernetesEfficiencyReportToken = *o.KubernetesEfficiencyReportToken
		}
		fKubernetesEfficiencyReportToken := frKubernetesEfficiencyReportToken
		if fKubernetesEfficiencyReportToken != "" {
			if err := r.SetFormParam("kubernetes_efficiency_report_token", fKubernetesEfficiencyReportToken); err != nil {
				return err
			}
		}
	}

	if o.StartDate != nil {

		// form param start_date
		var frStartDate string
		if o.StartDate != nil {
			frStartDate = *o.StartDate
		}
		fStartDate := frStartDate
		if fStartDate != "" {
			if err := r.SetFormParam("start_date", fStartDate); err != nil {
				return err
			}
		}
	}

	if o.WorkspaceToken != nil {

		// form param workspace_token
		var frWorkspaceToken string
		if o.WorkspaceToken != nil {
			frWorkspaceToken = *o.WorkspaceToken
		}
		fWorkspaceToken := frWorkspaceToken
		if fWorkspaceToken != "" {
			if err := r.SetFormParam("workspace_token", fWorkspaceToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamCreateKubernetesEfficiencyReportExport binds the parameter groupings
func (o *CreateKubernetesEfficiencyReportExportParams) bindParamGroupings(formats strfmt.Registry) []string {
	groupingsIR := o.Groupings

	var groupingsIC []string
	for _, groupingsIIR := range groupingsIR { // explode []string

		groupingsIIV := groupingsIIR // string as string
		groupingsIC = append(groupingsIC, groupingsIIV)
	}

	// items.CollectionFormat: "csv"
	groupingsIS := swag.JoinByFormat(groupingsIC, "csv")

	return groupingsIS
}
