// Code generated by go-swagger; DO NOT EDIT.

package scenario_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vantage-sh/vantage-go/vantagev2/models"
)

// GetScenarioModelsReader is a Reader for the GetScenarioModels structure.
type GetScenarioModelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScenarioModelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScenarioModelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /scenario_models] getScenarioModels", response, response.Code())
	}
}

// NewGetScenarioModelsOK creates a GetScenarioModelsOK with default headers values
func NewGetScenarioModelsOK() *GetScenarioModelsOK {
	return &GetScenarioModelsOK{}
}

/*
GetScenarioModelsOK describes a response with status code 200, with default header values.

Return all ScenarioModels.
*/
type GetScenarioModelsOK struct {
	Payload *models.ScenarioModels
}

// IsSuccess returns true when this get scenario models o k response has a 2xx status code
func (o *GetScenarioModelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get scenario models o k response has a 3xx status code
func (o *GetScenarioModelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get scenario models o k response has a 4xx status code
func (o *GetScenarioModelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get scenario models o k response has a 5xx status code
func (o *GetScenarioModelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get scenario models o k response a status code equal to that given
func (o *GetScenarioModelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get scenario models o k response
func (o *GetScenarioModelsOK) Code() int {
	return 200
}

func (o *GetScenarioModelsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scenario_models][%d] getScenarioModelsOK %s", 200, payload)
}

func (o *GetScenarioModelsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scenario_models][%d] getScenarioModelsOK %s", 200, payload)
}

func (o *GetScenarioModelsOK) GetPayload() *models.ScenarioModels {
	return o.Payload
}

func (o *GetScenarioModelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScenarioModels)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
