// Code generated by go-swagger; DO NOT EDIT.

package scenario_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetScenarioModelsParams creates a new GetScenarioModelsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetScenarioModelsParams() *GetScenarioModelsParams {
	return &GetScenarioModelsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetScenarioModelsParamsWithTimeout creates a new GetScenarioModelsParams object
// with the ability to set a timeout on a request.
func NewGetScenarioModelsParamsWithTimeout(timeout time.Duration) *GetScenarioModelsParams {
	return &GetScenarioModelsParams{
		timeout: timeout,
	}
}

// NewGetScenarioModelsParamsWithContext creates a new GetScenarioModelsParams object
// with the ability to set a context for a request.
func NewGetScenarioModelsParamsWithContext(ctx context.Context) *GetScenarioModelsParams {
	return &GetScenarioModelsParams{
		Context: ctx,
	}
}

// NewGetScenarioModelsParamsWithHTTPClient creates a new GetScenarioModelsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetScenarioModelsParamsWithHTTPClient(client *http.Client) *GetScenarioModelsParams {
	return &GetScenarioModelsParams{
		HTTPClient: client,
	}
}

/*
GetScenarioModelsParams contains all the parameters to send to the API endpoint

	for the get scenario models operation.

	Typically these are written to a http.Request.
*/
type GetScenarioModelsParams struct {

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Page.
	//
	// Format: int32
	Page *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get scenario models params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScenarioModelsParams) WithDefaults() *GetScenarioModelsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get scenario models params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetScenarioModelsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get scenario models params
func (o *GetScenarioModelsParams) WithTimeout(timeout time.Duration) *GetScenarioModelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scenario models params
func (o *GetScenarioModelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scenario models params
func (o *GetScenarioModelsParams) WithContext(ctx context.Context) *GetScenarioModelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scenario models params
func (o *GetScenarioModelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scenario models params
func (o *GetScenarioModelsParams) WithHTTPClient(client *http.Client) *GetScenarioModelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scenario models params
func (o *GetScenarioModelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get scenario models params
func (o *GetScenarioModelsParams) WithLimit(limit *int32) *GetScenarioModelsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get scenario models params
func (o *GetScenarioModelsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithPage adds the page to the get scenario models params
func (o *GetScenarioModelsParams) WithPage(page *int32) *GetScenarioModelsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get scenario models params
func (o *GetScenarioModelsParams) SetPage(page *int32) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetScenarioModelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int32

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
